function d(a){throw a;}var g=void 0,i=true,k=null,l=false;function aa(){return function(a){return a}}function ba(a){return function(b){this[a]=b}}function o(a){return function(){return this[a]}}function q(a){return function(){return a}}var r,ca=ca||{},t=this;function da(a,b){var c=a.split("."),e=t;!(c[0]in e)&&e.execScript&&e.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&u(b)?e[f]=b:e=e[f]?e[f]:e[f]={}}
function ea(a){for(var a=a.split("."),b=t,c;c=a.shift();)if(b[c]!=k)b=b[c];else return k;return b}function fa(){}function ga(a){a.va=function(){return a.$c||(a.$c=new a)}}
function v(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function u(a){return a!==g}function ha(a){return v(a)=="array"}function ia(a){var b=v(a);return b=="array"||b=="object"&&typeof a.length=="number"}function x(a){return typeof a=="string"}function ja(a){return v(a)=="function"}function ka(a){a=v(a);return a=="object"||a=="array"||a=="function"}function la(a){return a[ma]||(a[ma]=++oa)}var ma="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),oa=0;
function pa(a,b,c){return a.call.apply(a.bind,arguments)}function qa(a,b,c){a||d(Error());if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}function ra(a,b,c){ra=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?pa:qa;return ra.apply(k,arguments)}
function sa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var ta=Date.now||function(){return+new Date};function y(a,b){function c(){}c.prototype=b.prototype;a.e=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ua(){}ua.prototype.Ib=l;ua.prototype.J=function(){if(!this.Ib)this.Ib=i,this.i()};ua.prototype.i=function(){this.Qc&&va.apply(k,this.Qc)};function wa(a){a&&typeof a.J=="function"&&a.J()}function va(a){for(var b=0,c=arguments.length;b<c;++b){var e=arguments[b];ia(e)?va.apply(k,e):wa(e)}};function xa(a){this.stack=Error().stack||"";if(a)this.message=String(a)}y(xa,Error);xa.prototype.name="CustomError";function ya(a,b){for(var c=1;c<arguments.length;c++)var e=String(arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,e);return a}function za(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function Aa(a){if(!Ba.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(Ca,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(Da,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(Ea,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(Fa,"&quot;"));return a}
var Ca=/&/g,Da=/</g,Ea=/>/g,Fa=/\"/g,Ba=/[&<>\"]/,Ga={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},Ha={"'":"\\'"};
function Ia(a){var n;a=String(a);if(a.quote)return a.quote();else{for(var b=['"'],c=0;c<a.length;c++){var e=a.charAt(c),f=e.charCodeAt(0),h=b,j=c+1,m;if(!(m=Ga[e])){if(!(f>31&&f<127))if(e in Ha)e=Ha[e];else if(e in Ga)n=Ha[e]=Ga[e],e=n;else{f=e;m=e.charCodeAt(0);if(m>31&&m<127)f=e;else{if(m<256){if(f="\\x",m<16||m>256)f+="0"}else f="\\u",m<4096&&(f+="0");f+=m.toString(16).toUpperCase()}e=Ha[e]=f}m=e}h[j]=m}b.push('"');return b.join("")}}
function Ja(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}function Ka(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};function La(a,b){b.unshift(a);xa.call(this,ya.apply(k,b));b.shift();this.ud=a}y(La,xa);La.prototype.name="AssertionError";function Ma(a,b){d(new La("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};var z=Array.prototype,Na=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:c<0?Math.max(0,a.length+c):c;if(x(a))return!x(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Oa=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=x(a)?a.split(""):a,h=0;h<e;h++)h in f&&b.call(c,f[h],h,a)},Pa=z.map?function(a,b,c){return z.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=Array(e),h=x(a)?a.split(""):
a,j=0;j<e;j++)j in h&&(f[j]=b.call(c,h[j],j,a));return f},Qa=z.every?function(a,b,c){return z.every.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=x(a)?a.split(""):a,h=0;h<e;h++)if(h in f&&!b.call(c,f[h],h,a))return l;return i};function Ra(a,b){return Na(a,b)>=0}function Sa(a,b){var c=Na(a,b);c>=0&&z.splice.call(a,c,1)}function Ta(a){return z.concat.apply(z,arguments)}function Ua(a){if(ha(a))return Ta(a);else{for(var b=[],c=0,e=a.length;c<e;c++)b[c]=a[c];return b}}
function Va(a,b,c,e){z.splice.apply(a,Wa(arguments,1))}function Wa(a,b,c){return arguments.length<=2?z.slice.call(a,b):z.slice.call(a,b,c)};var Xa,Ya,Za,$a,ab,bb;function cb(){return t.navigator?t.navigator.userAgent:k}function db(){return t.navigator}ab=$a=Za=Ya=Xa=l;var eb;if(eb=cb()){var fb=db();Xa=eb.indexOf("Opera")==0;Ya=!Xa&&eb.indexOf("MSIE")!=-1;$a=(Za=!Xa&&eb.indexOf("WebKit")!=-1)&&eb.indexOf("Mobile")!=-1;ab=!Xa&&!Za&&fb.product=="Gecko"}var gb=Xa,A=Ya,hb=ab,B=Za,ib=$a,jb=db();bb=(jb&&jb.platform||"").indexOf("Mac")!=-1;var kb=!!db()&&(db().appVersion||"").indexOf("X11")!=-1,lb;
a:{var mb="",nb;if(gb&&t.opera)var ob=t.opera.version,mb=typeof ob=="function"?ob():ob;else if(hb?nb=/rv\:([^\);]+)(\)|;)/:A?nb=/MSIE\s+([^\);]+)(\)|;)/:B&&(nb=/WebKit\/(\S+)/),nb)var pb=nb.exec(cb()),mb=pb?pb[1]:"";if(A){var sb,tb=t.document;sb=tb?tb.documentMode:g;if(sb>parseFloat(mb)){lb=String(sb);break a}}lb=mb}var ub={};
function vb(a){var b;if(!(b=ub[a])){b=0;for(var c=za(String(lb)).split("."),e=za(String(a)).split("."),f=Math.max(c.length,e.length),h=0;b==0&&h<f;h++){var j=c[h]||"",m=e[h]||"",n=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var s=n.exec(j)||["","",""],w=p.exec(m)||["","",""];if(s[0].length==0&&w[0].length==0)break;b=Ja(s[1].length==0?0:parseInt(s[1],10),w[1].length==0?0:parseInt(w[1],10))||Ja(s[2].length==0,w[2].length==0)||Ja(s[2],w[2])}while(b==0)}b=ub[a]=b>=0}return b}var wb={};
function xb(){return wb[9]||(wb[9]=A&&document.documentMode&&document.documentMode>=9)};var yb=!A||xb(),zb=!A||xb(),Ab=A&&!vb("8");function Bb(a,b){this.type=a;this.currentTarget=this.target=b}y(Bb,ua);r=Bb.prototype;r.i=function(){delete this.type;delete this.target;delete this.currentTarget};r.ma=l;r.Xa=i;r.stopPropagation=function(){this.ma=i};r.preventDefault=function(){this.Xa=l};function Cb(a){Cb[" "](a);return a}Cb[" "]=fa;function Db(a,b){a&&this.Ra(a,b)}y(Db,Bb);var Eb=[1,4,2];r=Db.prototype;r.target=k;r.relatedTarget=k;r.offsetX=0;r.offsetY=0;r.clientX=0;r.clientY=0;r.screenX=0;r.screenY=0;r.button=0;r.keyCode=0;r.charCode=0;r.ctrlKey=l;r.altKey=l;r.shiftKey=l;r.metaKey=l;r.hd=l;r.w=k;
r.Ra=function(a,b){var c=this.type=a.type;Bb.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;if(e){if(hb){var f;a:{try{Cb(e.nodeName);f=i;break a}catch(h){}f=l}f||(e=k)}}else if(c=="mouseover")e=a.fromElement;else if(c=="mouseout")e=a.toElement;this.relatedTarget=e;this.offsetX=a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.hd=bb?a.metaKey:a.ctrlKey;this.state=a.state;this.w=a;delete this.Xa;delete this.ma};function Fb(a){return yb?a.w.button==0:a.type=="click"?i:!!(a.w.button&Eb[0])}
r.stopPropagation=function(){Db.e.stopPropagation.call(this);this.w.stopPropagation?this.w.stopPropagation():this.w.cancelBubble=i};r.preventDefault=function(){Db.e.preventDefault.call(this);var a=this.w;if(a.preventDefault)a.preventDefault();else if(a.returnValue=l,Ab)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};r.Sc=o("w");r.i=function(){Db.e.i.call(this);this.relatedTarget=this.currentTarget=this.target=this.w=k};function Gb(){}var Hb=0;r=Gb.prototype;r.key=0;r.na=l;r.Fb=l;r.Ra=function(a,b,c,e,f,h){ja(a)?this.xc=i:a&&a.handleEvent&&ja(a.handleEvent)?this.xc=l:d(Error("Invalid listener argument"));this.Aa=a;this.Ic=b;this.src=c;this.type=e;this.capture=!!f;this.nb=h;this.Fb=l;this.key=++Hb;this.na=l};r.handleEvent=function(a){return this.xc?this.Aa.call(this.nb||this.src,a):this.Aa.handleEvent.call(this.Aa,a)};function Ib(a,b,c){for(var e in a)b.call(c,a[e],e,a)}function Jb(a){var b=[],c=0,e;for(e in a)b[c++]=a[e];return b}function Kb(a){var b=[],c=0,e;for(e in a)b[c++]=e;return b}function Lb(a){var b={},c;for(c in a)b[c]=a[c];return b}var Mb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");
function Nb(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var h=0;h<Mb.length;h++)c=Mb[h],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};var Ob={},Pb={},Qb={},Rb={};
function C(a,b,c,e,f){if(b)if(ha(b)){for(var h=0;h<b.length;h++)C(a,b[h],c,e,f);return k}else{var e=!!e,j=Pb;b in j||(j[b]={n:0,A:0});j=j[b];e in j||(j[e]={n:0,A:0},j.n++);var j=j[e],m=la(a),n;j.A++;if(j[m]){n=j[m];for(h=0;h<n.length;h++)if(j=n[h],j.Aa==c&&j.nb==f){if(j.na)break;return n[h].key}}else n=j[m]=[],j.n++;h=Sb();h.src=a;j=new Gb;j.Ra(c,h,a,b,e,f);c=j.key;h.key=c;n.push(j);Ob[c]=j;Qb[m]||(Qb[m]=[]);Qb[m].push(j);a.addEventListener?(a==t||!a.fc)&&a.addEventListener(b,h,e):a.attachEvent(b in
Rb?Rb[b]:Rb[b]="on"+b,h);return c}else d(Error("Invalid event type"))}function Sb(){var a=Tb,b=zb?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function Ub(a,b,c,e,f){if(ha(b))for(var h=0;h<b.length;h++)Ub(a,b[h],c,e,f);else a=C(a,b,c,e,f),Ob[a].Fb=i}function Vb(a,b,c,e,f){if(ha(b))for(var h=0;h<b.length;h++)Vb(a,b[h],c,e,f);else if(e=!!e,a=Wb(a,b,e))for(h=0;h<a.length;h++)if(a[h].Aa==c&&a[h].capture==e&&a[h].nb==f){Xb(a[h].key);break}}
function Xb(a){if(!Ob[a])return l;var b=Ob[a];if(b.na)return l;var c=b.src,e=b.type,f=b.Ic,h=b.capture;c.removeEventListener?(c==t||!c.fc)&&c.removeEventListener(e,f,h):c.detachEvent&&c.detachEvent(e in Rb?Rb[e]:Rb[e]="on"+e,f);c=la(c);f=Pb[e][h][c];if(Qb[c]){var j=Qb[c];Sa(j,b);j.length==0&&delete Qb[c]}b.na=i;f.Bc=i;Yb(e,h,c,f);delete Ob[a];return i}
function Yb(a,b,c,e){if(!e.sb&&e.Bc){for(var f=0,h=0;f<e.length;f++)e[f].na?e[f].Ic.src=k:(f!=h&&(e[h]=e[f]),h++);e.length=h;e.Bc=l;h==0&&(delete Pb[a][b][c],Pb[a][b].n--,Pb[a][b].n==0&&(delete Pb[a][b],Pb[a].n--),Pb[a].n==0&&delete Pb[a])}}function Zb(a){var b,c=0,e=b==k;b=!!b;if(a==k)Ib(Qb,function(a){for(var f=a.length-1;f>=0;f--){var h=a[f];if(e||b==h.capture)Xb(h.key),c++}});else if(a=la(a),Qb[a])for(var a=Qb[a],f=a.length-1;f>=0;f--){var h=a[f];if(e||b==h.capture)Xb(h.key),c++}}
function Wb(a,b,c){var e=Pb;return b in e&&(e=e[b],c in e&&(e=e[c],a=la(a),e[a]))?e[a]:k}function $b(a,b,c,e,f){var h=1,b=la(b);if(a[b]){a.A--;a=a[b];a.sb?a.sb++:a.sb=1;try{for(var j=a.length,m=0;m<j;m++){var n=a[m];n&&!n.na&&(h&=ac(n,f)!==l)}}finally{a.sb--,Yb(c,e,b,a)}}return Boolean(h)}function ac(a,b){var c=a.handleEvent(b);a.Fb&&Xb(a.key);return c}
function Tb(a,b){if(!Ob[a])return i;var c=Ob[a],e=c.type,f=Pb;if(!(e in f))return i;var f=f[e],h,j;if(!zb){h=b||ea("window.event");var m=i in f,n=l in f;if(m){if(h.keyCode<0||h.returnValue!=g)return i;a:{var p=l;if(h.keyCode==0)try{h.keyCode=-1;break a}catch(s){p=i}if(p||h.returnValue==g)h.returnValue=i}}p=new Db;p.Ra(h,this);h=i;try{if(m){for(var w=[],I=p.currentTarget;I;I=I.parentNode)w.push(I);j=f[i];j.A=j.n;for(var M=w.length-1;!p.ma&&M>=0&&j.A;M--)p.currentTarget=w[M],h&=$b(j,w[M],e,i,p);if(n){j=
f[l];j.A=j.n;for(M=0;!p.ma&&M<w.length&&j.A;M++)p.currentTarget=w[M],h&=$b(j,w[M],e,l,p)}}else h=ac(c,p)}finally{if(w)w.length=0;p.J()}return h}e=new Db(b,this);try{h=ac(c,e)}finally{e.J()}return h};function bc(){}y(bc,ua);r=bc.prototype;r.fc=i;r.tb=k;r.Wb=ba("tb");r.addEventListener=function(a,b,c,e){C(this,a,b,c,e)};r.removeEventListener=function(a,b,c,e){Vb(this,a,b,c,e)};
r.dispatchEvent=function(a){var b=a.type||a,c=Pb;if(b in c){if(x(a))a=new Bb(a,this);else if(a instanceof Bb)a.target=a.target||this;else{var e=a,a=new Bb(b,this);Nb(a,e)}var e=1,f,c=c[b],b=i in c,h;if(b){f=[];for(h=this;h;h=h.tb)f.push(h);h=c[i];h.A=h.n;for(var j=f.length-1;!a.ma&&j>=0&&h.A;j--)a.currentTarget=f[j],e&=$b(h,f[j],a.type,i,a)&&a.Xa!=l}if(l in c)if(h=c[l],h.A=h.n,b)for(j=0;!a.ma&&j<f.length&&h.A;j++)a.currentTarget=f[j],e&=$b(h,f[j],a.type,l,a)&&a.Xa!=l;else for(f=this;!a.ma&&f&&h.A;f=
f.tb)a.currentTarget=f,e&=$b(h,f,a.type,l,a)&&a.Xa!=l;a=Boolean(e)}else a=i;return a};r.i=function(){bc.e.i.call(this);Zb(this);this.tb=k};var cc=t.window;function dc(a,b,c){ja(a)?c&&(a=ra(a,c)):a&&typeof a.handleEvent=="function"?a=ra(a.handleEvent,a):d(Error("Invalid listener argument"));return b>2147483647?-1:cc.setTimeout(a,b||0)};function ec(a){if(typeof a.ja=="function")return a.ja();if(x(a))return a.split("");if(ia(a)){for(var b=[],c=a.length,e=0;e<c;e++)b.push(a[e]);return b}return Jb(a)}function fc(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(ia(a)||x(a))Oa(a,b,c);else{var e;if(typeof a.Kb=="function")e=a.Kb();else if(typeof a.ja!="function")if(ia(a)||x(a)){e=[];for(var f=a.length,h=0;h<f;h++)e.push(h)}else e=Kb(a);else e=g;for(var f=ec(a),h=f.length,j=0;j<h;j++)b.call(c,f[j],e&&e[j],a)}};function gc(a,b){this.o={};this.k=[];var c=arguments.length;if(c>1){c%2&&d(Error("Uneven number of arguments"));for(var e=0;e<c;e+=2)this.set(arguments[e],arguments[e+1])}else a&&this.Cb(a)}r=gc.prototype;r.n=0;r.$b=0;r.ja=function(){hc(this);for(var a=[],b=0;b<this.k.length;b++)a.push(this.o[this.k[b]]);return a};r.Kb=function(){hc(this);return this.k.concat()};r.clear=function(){this.o={};this.$b=this.n=this.k.length=0};
r.remove=function(a){return ic(this.o,a)?(delete this.o[a],this.n--,this.$b++,this.k.length>2*this.n&&hc(this),i):l};function hc(a){if(a.n!=a.k.length){for(var b=0,c=0;b<a.k.length;){var e=a.k[b];ic(a.o,e)&&(a.k[c++]=e);b++}a.k.length=c}if(a.n!=a.k.length){for(var f={},c=b=0;b<a.k.length;)e=a.k[b],ic(f,e)||(a.k[c++]=e,f[e]=1),b++;a.k.length=c}}r.set=function(a,b){ic(this.o,a)||(this.n++,this.k.push(a),this.$b++);this.o[a]=b};
r.Cb=function(a){var b;a instanceof gc?(b=a.Kb(),a=a.ja()):(b=Kb(a),a=Jb(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};r.H=function(){return new gc(this)};function ic(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function jc(a){this.o=new gc;a&&this.Cb(a)}function kc(a){var b=typeof a;return b=="object"&&a||b=="function"?"o"+la(a):b.substr(0,1)+a}r=jc.prototype;r.add=function(a){this.o.set(kc(a),a)};r.Cb=function(a){for(var a=ec(a),b=a.length,c=0;c<b;c++)this.add(a[c])};r.ub=function(a){for(var a=ec(a),b=a.length,c=0;c<b;c++)this.remove(a[c])};r.remove=function(a){return this.o.remove(kc(a))};r.clear=function(){this.o.clear()};r.contains=function(a){a=kc(a);return ic(this.o.o,a)};
r.uc=function(a){for(var b=new jc,a=ec(a),c=0;c<a.length;c++){var e=a[c];this.contains(e)&&b.add(e)}return b};r.ja=function(){return this.o.ja()};r.H=function(){return new jc(this)};function lc(a){return mc(a||arguments.callee.caller,[])}
function mc(a,b){var c=[];if(Ra(b,a))c.push("[...circular reference...]");else if(a&&b.length<50){c.push(nc(a)+"(");for(var e=a.arguments,f=0;f<e.length;f++){f>0&&c.push(", ");var h;h=e[f];switch(typeof h){case "object":h=h?"object":"null";break;case "string":break;case "number":h=String(h);break;case "boolean":h=h?"true":"false";break;case "function":h=(h=nc(h))?h:"[fn]";break;default:h=typeof h}h.length>40&&(h=h.substr(0,40)+"...");c.push(h)}b.push(a);c.push(")\n");try{c.push(mc(a.caller,b))}catch(j){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function nc(a){if(oc[a])return oc[a];a=String(a);if(!oc[a]){var b=/function ([^\(]+)/.exec(a);oc[a]=b?b[1]:"[Anonymous]"}return oc[a]}var oc={};function pc(a,b,c,e,f){this.reset(a,b,c,e,f)}pc.prototype.ld=0;pc.prototype.ic=k;pc.prototype.hc=k;var qc=0;pc.prototype.reset=function(a,b,c,e,f){this.ld=typeof f=="number"?f:qc++;this.wd=e||ta();this.Va=a;this.cd=b;this.sd=c;delete this.ic;delete this.hc};pc.prototype.Kc=ba("Va");function rc(a){this.dd=a}rc.prototype.q=k;rc.prototype.Va=k;rc.prototype.Y=k;rc.prototype.rc=k;function sc(a,b){this.name=a;this.value=b}sc.prototype.toString=o("name");var tc=new sc("SEVERE",1E3),uc=new sc("WARNING",900),vc=new sc("CONFIG",700),wc=new sc("FINE",500),xc=new sc("FINEST",300);rc.prototype.getParent=o("q");rc.prototype.Kc=ba("Va");function yc(a){if(a.Va)return a.Va;if(a.q)return yc(a.q);Ma("Root logger has no level set.");return k}
rc.prototype.log=function(a,b,c){if(a.value>=yc(this).value){a=this.Tc(a,b,c);b="log:"+a.cd;t.console&&(t.console.timeStamp?t.console.timeStamp(b):t.console.markTimeline&&t.console.markTimeline(b));t.msWriteProfilerMark&&t.msWriteProfilerMark(b);for(b=this;b;){var c=b,e=a;if(c.rc)for(var f=0,h=g;h=c.rc[f];f++)h(e);b=b.getParent()}}};
rc.prototype.Tc=function(a,b,c){var e=new pc(a,String(b),this.dd);if(c){e.ic=c;var f;var h=arguments.callee.caller;try{var j;var m=ea("window.location.href");if(x(c))j={message:c,name:"Unknown error",lineNumber:"Not available",fileName:m,stack:"Not available"};else{var n,p,s=l;try{n=c.lineNumber||c.rd||"Not available"}catch(w){n="Not available",s=i}try{p=c.fileName||c.filename||c.sourceURL||m}catch(I){p="Not available",s=i}j=s||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:n,
fileName:p,stack:c.stack||"Not available"}:c}f="Message: "+Aa(j.message)+'\nUrl: <a href="view-source:'+j.fileName+'" target="_new">'+j.fileName+"</a>\nLine: "+j.lineNumber+"\n\nBrowser stack:\n"+Aa(j.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+Aa(lc(h)+"-> ")}catch(M){f="Exception trying to expose exception! You win, we lose. "+M}e.hc=f}return e};function D(a,b){a.log(wc,b,g)}var zc={},Ac=k;
function Bc(a){Ac||(Ac=new rc(""),zc[""]=Ac,Ac.Kc(vc));var b;if(!(b=zc[a])){b=new rc(a);var c=a.lastIndexOf("."),e=a.substr(c+1),c=Bc(a.substr(0,c));if(!c.Y)c.Y={};c.Y[e]=b;b.q=c;zc[a]=b}return b};function Cc(){}Cc.prototype.fb=k;var Dc;function Gc(){}y(Gc,Cc);function Hc(a){return(a=Ic(a))?new ActiveXObject(a):new XMLHttpRequest}function Jc(a){var b={};Ic(a)&&(b[0]=i,b[1]=i);return b}Gc.prototype.Nb=k;
function Ic(a){if(!a.Nb&&typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var e=b[c];try{return new ActiveXObject(e),a.Nb=e}catch(f){}}d(Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.Nb}Dc=new Gc;function Kc(){if(hb)this.ga={},this.Bb={},this.yb=[]}Kc.prototype.m=Bc("goog.net.xhrMonitor");Kc.prototype.ib=hb;function Lc(a){var b=Mc;if(b.ib){var c=x(a)?a:ka(a)?la(a):"";b.m.log(xc,"Pushing context: "+a+" ("+c+")",g);b.yb.push(c)}}function Nc(){var a=Mc;if(a.ib){var b=a.yb.pop();a.m.log(xc,"Popping context: "+b,g);Oc(a,b)}}function Pc(a){var b=Mc;if(b.ib){a=la(a);D(b.m,"Opening XHR : "+a);for(var c=0;c<b.yb.length;c++){var e=b.yb[c];Qc(b.ga,e,a);Qc(b.Bb,a,e)}}}
function Oc(a,b){var c=a.Bb[b],e=a.ga[b];c&&e&&(a.m.log(xc,"Updating dependent contexts",g),Oa(c,function(a){Oa(e,function(b){Qc(this.ga,a,b);Qc(this.Bb,b,a)},this)},a))}function Qc(a,b,c){a[b]||(a[b]=[]);Ra(a[b],c)||a[b].push(c)}var Mc=new Kc;var Rc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Sc(a){this.headers=new gc;this.Ea=a||k}y(Sc,bc);Sc.prototype.m=Bc("goog.net.XhrIo");var Tc=/^https?:?$/i,Uc=[];function Vc(a,b,c,e,f,h){var j=new Sc;Uc.push(j);b&&C(j,"complete",b);C(j,"ready",sa(Wc,j));if(h)j.bb=Math.max(0,h);j.send(a,c,e,f)}function Wc(a){a.J();Sa(Uc,a)}r=Sc.prototype;r.W=l;r.f=k;r.Ab=k;r.Ua="";r.zc="";r.Sa=0;r.Ta="";r.Jb=l;r.pb=l;r.Ob=l;r.la=l;r.bb=0;r.oa=k;r.Jc="";r.pd=l;
r.send=function(a,b,c,e){this.f&&d(Error("[goog.net.XhrIo] Object is active with another request"));b=b?b.toUpperCase():"GET";this.Ua=a;this.Ta="";this.Sa=0;this.zc=b;this.Jb=l;this.W=i;this.f=this.Ea?Hc(this.Ea):Hc(Dc);this.Ab=this.Ea?this.Ea.fb||(this.Ea.fb=Jc(this.Ea)):Dc.fb||(Dc.fb=Jc(Dc));Pc(this.f);this.f.onreadystatechange=ra(this.Ec,this);try{D(this.m,Xc(this,"Opening Xhr")),this.Ob=i,this.f.open(b,a,i),this.Ob=l}catch(f){D(this.m,Xc(this,"Error opening Xhr: "+f.message));Yc(this,f);return}var a=
c||"",h=this.headers.H();e&&fc(e,function(a,b){h.set(b,a)});b=="POST"&&!ic(h.o,"Content-Type")&&h.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");fc(h,function(a,b){this.f.setRequestHeader(b,a)},this);if(this.Jc)this.f.responseType=this.Jc;if("withCredentials"in this.f)this.f.withCredentials=this.pd;try{if(this.oa)cc.clearTimeout(this.oa),this.oa=k;if(this.bb>0)D(this.m,Xc(this,"Will abort after "+this.bb+"ms if incomplete")),this.oa=cc.setTimeout(ra(this.od,this),this.bb);D(this.m,
Xc(this,"Sending request"));this.pb=i;this.f.send(a);this.pb=l}catch(j){D(this.m,Xc(this,"Send error: "+j.message)),Yc(this,j)}};r.dispatchEvent=function(a){if(this.f){Lc(this.f);try{return Sc.e.dispatchEvent.call(this,a)}finally{Nc()}}else return Sc.e.dispatchEvent.call(this,a)};r.od=function(){if(typeof ca!="undefined"&&this.f)this.Ta="Timed out after "+this.bb+"ms, aborting",this.Sa=8,D(this.m,Xc(this,this.Ta)),this.dispatchEvent("timeout"),this.abort(8)};
function Yc(a,b){a.W=l;if(a.f)a.la=i,a.f.abort(),a.la=l;a.Ta=b;a.Sa=5;Zc(a);$c(a)}function Zc(a){if(!a.Jb)a.Jb=i,a.dispatchEvent("complete"),a.dispatchEvent("error")}r.abort=function(a){if(this.f&&this.W)D(this.m,Xc(this,"Aborting")),this.W=l,this.la=i,this.f.abort(),this.la=l,this.Sa=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),$c(this)};r.i=function(){if(this.f){if(this.W)this.W=l,this.la=i,this.f.abort(),this.la=l;$c(this,i)}Sc.e.i.call(this)};
r.Ec=function(){!this.Ob&&!this.pb&&!this.la?this.gd():ad(this)};r.gd=function(){ad(this)};
function ad(a){if(a.W&&typeof ca!="undefined")if(a.Ab[1]&&bd(a)==4&&cd(a)==2)D(a.m,Xc(a,"Local request error detected and ignored"));else if(a.pb&&bd(a)==4)cc.setTimeout(ra(a.Ec,a),0);else if(a.dispatchEvent("readystatechange"),bd(a)==4){D(a.m,Xc(a,"Request complete"));a.W=l;var b;a:switch(cd(a)){case 0:b=x(a.Ua)?a.Ua.match(Rc)[1]||k:a.Ua.qd();b=!(b?Tc.test(b):self.location?Tc.test(self.location.protocol):1);break a;case 200:case 201:case 202:case 204:case 304:case 1223:b=i;break a;default:b=l}if(b)a.dispatchEvent("complete"),
a.dispatchEvent("success");else{a.Sa=6;var c;try{c=bd(a)>2?a.f.statusText:""}catch(e){D(a.m,"Can not get status: "+e.message),c=""}a.Ta=c+" ["+cd(a)+"]";Zc(a)}$c(a)}}
function $c(a,b){if(a.f){var c=a.f,e=a.Ab[0]?fa:k;a.f=k;a.Ab=k;if(a.oa)cc.clearTimeout(a.oa),a.oa=k;b||(Lc(c),a.dispatchEvent("ready"),Nc());var f=Mc;if(f.ib){var h=la(c);D(f.m,"Closing XHR : "+h);delete f.Bb[h];for(var j in f.ga)Sa(f.ga[j],h),f.ga[j].length==0&&delete f.ga[j]}try{c.onreadystatechange=e}catch(m){a.m.log(tc,"Problem encountered resetting onreadystatechange: "+m.message,g)}}}r.vc=function(){return!!this.f};function bd(a){return a.f?a.f.readyState:0}
function cd(a){try{return bd(a)>2?a.f.status:-1}catch(b){return a.m.log(uc,"Can not get status: "+b.message,g),-1}}function dd(a){try{return a.f?a.f.responseText:""}catch(b){return D(a.m,"Can not get responseText: "+b.message),""}}function Xc(a,b){return b+" ["+a.zc+" "+a.Ua+" "+cd(a)+"]"};var ed;(ed="ScriptEngine"in t&&t.ScriptEngine()=="JScript")&&(t.ScriptEngineMajorVersion(),t.ScriptEngineMinorVersion(),t.ScriptEngineBuildVersion());function fd(a,b){this.F=ed?[]:"";a!=k&&this.append.apply(this,arguments)}fd.prototype.set=function(a){this.clear();this.append(a)};ed?(fd.prototype.Eb=0,fd.prototype.append=function(a,b,c){b==k?this.F[this.Eb++]=a:(this.F.push.apply(this.F,arguments),this.Eb=this.F.length);return this}):fd.prototype.append=function(a,b,c){this.F+=a;if(b!=k)for(var e=1;e<arguments.length;e++)this.F+=arguments[e];return this};fd.prototype.clear=function(){ed?this.Eb=this.F.length=0:this.F=""};
fd.prototype.toString=function(){if(ed){var a=this.F.join("");this.clear();a&&this.append(a);return a}else return this.F};function E(a,b){this.x=u(a)?a:0;this.y=u(b)?b:0}E.prototype.H=function(){return new E(this.x,this.y)};E.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function gd(a,b){return new E(a.x-b.x,a.y-b.y)};function hd(a,b,c,e){this.top=a;this.right=b;this.bottom=c;this.left=e}hd.prototype.H=function(){return new hd(this.top,this.right,this.bottom,this.left)};hd.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};hd.prototype.contains=function(a){return!this||!a?l:a instanceof hd?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};var id,jd=!A||xb();!hb&&!A||A&&xb()||hb&&vb("1.9.1");var kd=A&&!vb("9");function ld(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function md(a,b){var c=ld(a),e=Wa(arguments,1),f;f=c;for(var h=0,j=0;j<e.length;j++)Ra(f,e[j])||(f.push(e[j]),h++);f=h==e.length;a.className=c.join(" ");return f}function nd(a,b){var c=ld(a),e=Wa(arguments,1),f;f=c;for(var h=0,j=0;j<f.length;j++)Ra(e,f[j])&&(Va(f,j--,1),h++);f=h==e.length;a.className=c.join(" ");return f};function od(a,b){this.width=a;this.height=b}od.prototype.H=function(){return new od(this.width,this.height)};od.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};od.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};od.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function pd(a){return a?new qd(F(a)):id||(id=new qd)}function G(a){return x(a)?document.getElementById(a):a}function rd(a,b){Ib(b,function(b,e){e=="style"?a.style.cssText=b:e=="class"?a.className=b:e=="for"?a.htmlFor=b:e in sd?a.setAttribute(sd[e],b):e.lastIndexOf("aria-",0)==0?a.setAttribute(e,b):a[e]=b})}
var sd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};function td(a,b,c,e){function f(c){c&&b.appendChild(x(c)?a.createTextNode(c):c)}for(;e<c.length;e++){var h=c[e];ia(h)&&!(ka(h)&&h.nodeType>0)?Oa(ud(h)?Ua(h):h,f):f(h)}}function vd(a){a&&a.parentNode&&a.parentNode.removeChild(a)}
function wd(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function F(a){return a.nodeType==9?a:a.ownerDocument||a.document}function xd(a,b){var c=[];yd(a,b,c,l);return c}function yd(a,b,c,e){if(a!=k)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),e))return i;if(yd(a,b,c,e))return i;a=a.nextSibling}return l}
var zd={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Ad={IMG:" ",BR:"\n"};function Bd(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?(a=a.tabIndex,typeof a=="number"&&a>=0&&a<32768):l}function Cd(a){var b=[];Dd(a,b,l);return b.join("")}function Dd(a,b,c){if(!(a.nodeName in zd))if(a.nodeType==3)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Ad)b.push(Ad[a.nodeName]);else for(a=a.firstChild;a;)Dd(a,b,c),a=a.nextSibling}
function ud(a){if(a&&typeof a.length=="number")if(ka(a))return typeof a.item=="function"||typeof a.item=="string";else if(ja(a))return typeof a.item=="function";return l}function qd(a){this.j=a||t.document||document}r=qd.prototype;r.Ma=pd;r.c=function(a){return x(a)?this.j.getElementById(a):a};
r.u=function(a,b,c){var e=this.j,f=arguments,h=f[0],j=f[1];if(!jd&&j&&(j.name||j.type)){h=["<",h];j.name&&h.push(' name="',Aa(j.name),'"');if(j.type){h.push(' type="',Aa(j.type),'"');var m={};Nb(m,j);j=m;delete j.type}h.push(">");h=h.join("")}h=e.createElement(h);if(j)x(j)?h.className=j:ha(j)?md.apply(k,[h].concat(j)):rd(h,j);f.length>2&&td(e,h,f,2);return h};r.createElement=function(a){return this.j.createElement(a)};r.createTextNode=function(a){return this.j.createTextNode(a)};
function Ed(a){return a.j.compatMode=="CSS1Compat"}function Fd(a){var b=a.j,a=!B&&b.compatMode=="CSS1Compat"?b.documentElement:b.body,b=b.parentWindow||b.defaultView;return new E(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}r.appendChild=function(a,b){a.appendChild(b)};r.append=function(a,b){td(F(a),a,arguments,1)};r.contains=wd;function Gd(a,b,c,e){this.left=a;this.top=b;this.width=c;this.height=e}Gd.prototype.H=function(){return new Gd(this.left,this.top,this.width,this.height)};Gd.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
Gd.prototype.uc=function(a){var b=Math.max(this.left,a.left),c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var e=Math.max(this.top,a.top),a=Math.min(this.top+this.height,a.top+a.height);if(e<=a)return this.left=b,this.top=e,this.width=c-b,this.height=a-e,i}return l};
Gd.prototype.contains=function(a){return a instanceof Gd?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};function Hd(a,b){var c=F(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,k))?c[b]||c.getPropertyValue(b):""}function Jd(a,b){return a.currentStyle?a.currentStyle[b]:k}function Kd(a,b){return Hd(a,b)||Jd(a,b)||a.style[b]}function Ld(a){a=a?a.nodeType==9?a:F(a):document;return A&&!xb()&&!Ed(pd(a))?a.body:a.documentElement}
function Md(a){var b=a.getBoundingClientRect();if(A)a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop;return b}
function Nd(a){if(A)return a.offsetParent;for(var b=F(a),c=Kd(a,"position"),e=c=="fixed"||c=="absolute",a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Kd(a,"position"),e=e&&c=="static"&&a!=b.documentElement&&a!=b.body,!e&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"||c=="relative"))return a;return k}
function Od(a){for(var b=new hd(0,Infinity,Infinity,0),c=pd(a),e=c.j.body,f=c.j.documentElement,h=!B&&c.j.compatMode=="CSS1Compat"?c.j.documentElement:c.j.body;a=Nd(a);)if((!A||a.clientWidth!=0)&&(!B||a.clientHeight!=0||a!=e)&&a!=e&&a!=f&&Kd(a,"overflow")!="visible"){var j=Pd(a),m;m=a;if(hb&&!vb("1.9")){var n=parseFloat(Hd(m,"borderLeftWidth"));if(Qd(m)){var p=m.offsetWidth-m.clientWidth-n-parseFloat(Hd(m,"borderRightWidth"));n+=p}m=new E(n,parseFloat(Hd(m,"borderTopWidth")))}else m=new E(m.clientLeft,
m.clientTop);j.x+=m.x;j.y+=m.y;b.top=Math.max(b.top,j.y);b.right=Math.min(b.right,j.x+a.clientWidth);b.bottom=Math.min(b.bottom,j.y+a.clientHeight);b.left=Math.max(b.left,j.x)}e=h.scrollLeft;h=h.scrollTop;b.left=Math.max(b.left,e);b.top=Math.max(b.top,h);c=c.j.parentWindow||c.j.defaultView||window;f=c.document;B&&!vb("500")&&!ib?(typeof c.innerHeight=="undefined"&&(c=window),f=c.innerHeight,a=c.document.documentElement.scrollHeight,c==c.top&&a<f&&(f-=15),c=new od(c.innerWidth,f)):(c=f.compatMode==
"CSS1Compat"?f.documentElement:f.body,c=new od(c.clientWidth,c.clientHeight));b.right=Math.min(b.right,e+c.width);b.bottom=Math.min(b.bottom,h+c.height);return b.top>=0&&b.left>=0&&b.bottom>b.top&&b.right>b.left?b:k}
function Pd(a){var b,c=F(a),e=Kd(a,"position"),f=hb&&c.getBoxObjectFor&&!a.getBoundingClientRect&&e=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),h=new E(0,0),j=Ld(c);if(a==j)return h;if(a.getBoundingClientRect)b=Md(a),a=Fd(pd(c)),h.x=b.left+a.x,h.y=b.top+a.y;else if(c.getBoxObjectFor&&!f)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(j),h.x=b.screenX-a.screenX,h.y=b.screenY-a.screenY;else{b=a;do{h.x+=b.offsetLeft;h.y+=b.offsetTop;b!=a&&(h.x+=b.clientLeft||0,h.y+=b.clientTop||0);if(B&&
Kd(b,"position")=="fixed"){h.x+=c.body.scrollLeft;h.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(gb||B&&e=="absolute")h.y-=c.body.offsetTop;for(b=a;(b=Nd(b))&&b!=c.body&&b!=j;)if(h.x-=b.scrollLeft,!gb||b.tagName!="TR")h.y-=b.scrollTop}return h}function Rd(a,b){typeof a=="number"&&(a=(b?Math.round(a):a)+"px");return a}
function Sd(a){if(Kd(a,"display")!="none")return Td(a);var b=a.style,c=b.display,e=b.visibility,f=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Td(a);b.display=c;b.position=f;b.visibility=e;return a}function Td(a){var b=a.offsetWidth,c=a.offsetHeight,e=B&&!b&&!c;return(!u(b)||e)&&a.getBoundingClientRect?(a=Md(a),new od(a.right-a.left,a.bottom-a.top)):new od(b,c)}function Ud(a,b){a.style.display=b?"":"none"}function Qd(a){return"rtl"==Kd(a,"direction")}
var Vd=hb?"MozUserSelect":B?"WebkitUserSelect":k;function Wd(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var c=a.style.left,e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var f=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=e;return f}}var Xd={thin:2,medium:4,thick:6};function Yd(a,b){if(Jd(a,b+"Style")=="none")return 0;var c=Jd(a,b+"Width");return c in Xd?Xd[c]:Wd(a,c)};function Zd(a,b,c,e,f,h,j,m){var n,p=c.offsetParent;if(p){var s=p.tagName=="HTML"||p.tagName=="BODY";if(!s||Kd(p,"position")!="static")n=Pd(p),s||(n=gd(n,new E(p.scrollLeft,p.scrollTop)))}p=Pd(a);s=Sd(a);p=new Gd(p.x,p.y,s.width,s.height);(s=Od(a))&&p.uc(new Gd(s.left,s.top,s.right-s.left,s.bottom-s.top));var s=pd(a),w=pd(c);if(s.j!=w.j){var I=s.j.body,w=w.j.parentWindow||w.j.defaultView,M=new E(0,0),qb=F(I)?F(I).parentWindow||F(I).defaultView:window,Id=I;do{var na;if(qb==w)na=Pd(Id);else{var O=Id;
na=new E;if(O.nodeType==1)if(O.getBoundingClientRect)O=Md(O),na.x=O.left,na.y=O.top;else{var Ec=Fd(pd(O)),O=Pd(O);na.x=O.x-Ec.x;na.y=O.y-Ec.y}else{var Ec=ja(O.Sc),Fc=O;O.targetTouches?Fc=O.targetTouches[0]:Ec&&O.w.targetTouches&&(Fc=O.w.targetTouches[0]);na.x=Fc.clientX;na.y=Fc.clientY}}M.x+=na.x;M.y+=na.y}while(qb&&qb!=w&&(Id=qb.frameElement)&&(qb=qb.parent));I=gd(M,Pd(I));A&&!Ed(s)&&(I=gd(I,Fd(s)));p.left+=I.x;p.top+=I.y}a=(b&4&&Qd(a)?b^2:b)&-5;b=new E(a&2?p.left+p.width:p.left,a&1?p.top+p.height:
p.top);n&&(b=gd(b,n));f&&(b.x+=(a&2?-1:1)*f.x,b.y+=(a&1?-1:1)*f.y);var rb;if(j&&(rb=Od(c))&&n)rb.top-=n.y,rb.right-=n.x,rb.bottom-=n.y,rb.left-=n.x;return $d(b,c,e,h,rb,j,m)}
function $d(a,b,c,e,f,h,j){var a=a.H(),m=0,n=(c&4&&Qd(b)?c^2:c)&-5,c=Sd(b),j=j?j.H():c.H();if(e||n!=0)n&2?a.x-=j.width+(e?e.right:0):e&&(a.x+=e.left),n&1?a.y-=j.height+(e?e.bottom:0):e&&(a.y+=e.top);if(h){if(f){m=a;e=0;if((h&65)==65&&(m.x<f.left||m.x>=f.right))h&=-2;if((h&132)==132&&(m.y<f.top||m.y>=f.bottom))h&=-5;if(m.x<f.left&&h&1)m.x=f.left,e|=1;m.x<f.left&&m.x+j.width>f.right&&h&16&&(j.width-=m.x+j.width-f.right,e|=4);if(m.x+j.width>f.right&&h&1)m.x=Math.max(f.right-j.width,f.left),e|=1;h&2&&
(e|=(m.x<f.left?16:0)|(m.x+j.width>f.right?32:0));if(m.y<f.top&&h&4)m.y=f.top,e|=2;m.y>=f.top&&m.y+j.height>f.bottom&&h&32&&(j.height-=m.y+j.height-f.bottom,e|=8);if(m.y+j.height>f.bottom&&h&4)m.y=Math.max(f.bottom-j.height,f.top),e|=2;h&8&&(e|=(m.y<f.top?64:0)|(m.y+j.height>f.bottom?128:0));m=e}else m=256;if(m&496)return m}h=a;f=hb&&(bb||kb)&&vb("1.9");h instanceof E?(a=h.x,h=h.y):(a=h,h=g);b.style.left=Rd(a,f);b.style.top=Rd(h,f);if(!(c==j||(!c||!j?0:c.width==j.width&&c.height==j.height)))a=Ed(pd(F(b))),
A&&(!a||!vb("8"))?(c=b.style,a?(A?(a=Wd(b,Jd(b,"paddingLeft")),f=Wd(b,Jd(b,"paddingRight")),h=Wd(b,Jd(b,"paddingTop")),e=Wd(b,Jd(b,"paddingBottom")),a=new hd(h,f,e,a)):(a=Hd(b,"paddingLeft"),f=Hd(b,"paddingRight"),h=Hd(b,"paddingTop"),e=Hd(b,"paddingBottom"),a=new hd(parseFloat(h),parseFloat(f),parseFloat(e),parseFloat(a))),A?(f=Yd(b,"borderLeft"),h=Yd(b,"borderRight"),e=Yd(b,"borderTop"),b=Yd(b,"borderBottom"),b=new hd(e,h,b,f)):(f=Hd(b,"borderLeftWidth"),h=Hd(b,"borderRightWidth"),e=Hd(b,"borderTopWidth"),
b=Hd(b,"borderBottomWidth"),b=new hd(parseFloat(e),parseFloat(h),parseFloat(b),parseFloat(f))),c.pixelWidth=j.width-b.left-a.left-a.right-b.right,c.pixelHeight=j.height-b.top-a.top-a.bottom-b.bottom):(c.pixelWidth=j.width,c.pixelHeight=j.height)):(b=b.style,hb?b.MozBoxSizing="border-box":B?b.WebkitBoxSizing="border-box":b.boxSizing="border-box",b.width=j.width+"px",b.height=j.height+"px");return m};function ae(){}ae.prototype.L=function(){};function be(a,b){this.element=a;this.ec=b}y(be,ae);be.prototype.L=function(a,b,c){Zd(this.element,this.ec,a,b,g,c)};function ce(a){this.z=a;this.k=[]}y(ce,ua);var de=[];function H(a,b,c,e,f){ha(c)||(de[0]=c,c=de);for(var h=0;h<c.length;h++)a.k.push(C(b,c[h],e||a,f||l,a.z||a));return a}function ee(a,b,c,e,f,h){if(ha(c))for(var j=0;j<c.length;j++)ee(a,b,c[j],e,f,h);else{a:{e=e||a;h=h||a.z||a;f=!!f;if(b=Wb(b,c,f))for(c=0;c<b.length;c++)if(!b[c].na&&b[c].Aa==e&&b[c].capture==f&&b[c].nb==h){b=b[c];break a}b=k}if(b)b=b.key,Xb(b),Sa(a.k,b)}return a}ce.prototype.ub=function(){Oa(this.k,Xb);this.k.length=0};
ce.prototype.i=function(){ce.e.i.call(this);this.ub()};ce.prototype.handleEvent=function(){d(Error("EventHandler.handleEvent not implemented"))};function fe(a,b){this.Gb=a instanceof E?a:new E(a,b)}y(fe,ae);fe.prototype.L=function(a,b,c,e){Zd(Ld(a),0,a,b,this.Gb,c,k,e)};function ge(a,b,c,e,f){if(!A&&(!B||!vb("525")))return i;if(bb&&f)return he(a);if(f&&!e)return l;if(!c&&(b==17||b==18))return l;if(A&&e&&b==a)return l;switch(a){case 13:return!(A&&xb());case 27:return!B}return he(a)}
function he(a){if(a>=48&&a<=57)return i;if(a>=96&&a<=106)return i;if(a>=65&&a<=90)return i;if(B&&a==0)return i;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return i;default:return l}};function ie(a,b){this.z=new ce(this);this.Vb(a||k);if(b)this.Da=b}y(ie,bc);r=ie.prototype;r.b=k;r.Oc=i;r.ac=k;r.ya=l;r.md=l;r.Qb=-1;r.yc=-1;r.Yc=l;r.Rc=i;r.Da="toggle_display";r.c=o("b");r.Vb=function(a){this.ya&&d(Error("Can not change this state of the popup while showing."));this.b=a};r.D=o("ya");
r.M=function(a){this.$a&&this.$a.stop();this.Qa&&this.Qa.stop();if(a){if(!this.ya&&this.Rb()){this.b||d(Error("Caller must call setElement before trying to show the popup"));this.L();a=F(this.b);this.Yc&&H(this.z,a,"keydown",this.fd,i);if(this.Oc)if(H(this.z,a,"mousedown",this.Dc,i),A){var b;try{b=a.activeElement}catch(c){}for(;b&&b.nodeName=="IFRAME";){try{var e=b.contentDocument||b.contentWindow.document}catch(f){break}a=e;b=a.activeElement}H(this.z,a,"mousedown",this.Dc,i);H(this.z,a,"deactivate",
this.Cc)}else H(this.z,a,"blur",this.Cc);this.Da=="toggle_display"?(this.b.style.visibility="visible",Ud(this.b,i)):this.Da=="move_offscreen"&&this.L();this.ya=i;this.$a?(Ub(this.$a,"end",this.Fc,l,this),this.$a.play()):this.Fc()}}else je(this)};r.L=fa;function je(a,b){if(!a.ya||!a.dispatchEvent({type:"beforehide",target:b}))return l;a.z&&a.z.ub();a.Qa?(Ub(a.Qa,"end",sa(a.dc,b),l,a),a.Qa.play()):a.dc(b);return i}
r.dc=function(a){if(this.Da=="toggle_display")this.md?dc(this.sc,0,this):this.sc();else if(this.Da=="move_offscreen")this.b.style.left="-200px",this.b.style.top="-200px";this.ya=l;this.Sb(a)};r.sc=function(){this.b.style.visibility="hidden";Ud(this.b,l)};r.Rb=function(){return this.dispatchEvent("beforeshow")};r.Fc=function(){this.Qb=ta();this.yc=-1;this.dispatchEvent("show")};r.Sb=function(a){this.yc=ta();this.dispatchEvent({type:"hide",target:a})};
r.Dc=function(a){a=a.target;!wd(this.b,a)&&(!this.ac||wd(this.ac,a))&&!(ta()-this.Qb<150)&&je(this,a)};r.fd=function(a){a.keyCode==27&&je(this,a.target)&&(a.preventDefault(),a.stopPropagation())};r.Cc=function(a){if(this.Rc){var b=F(this.b);if(A||gb){if(a=b.activeElement,!a||wd(this.b,a)||a.tagName=="BODY")return}else if(a.target!=b)return;ta()-this.Qb<150||je(this)}};r.i=function(){ie.e.i.call(this);this.z.J();wa(this.$a);wa(this.Qa);delete this.b;delete this.z};function ke(a,b){this.jd=4;this.Tb=b||g;ie.call(this,a)}y(ke,ie);ke.prototype.L=function(){if(this.Tb){var a=!this.D()&&this.Da!="move_offscreen",b=this.c();if(a)b.style.visibility="hidden",Ud(b,i);this.Tb.L(b,this.jd,this.td);a&&Ud(b,l)}};function J(a,b,c){this.v=c||(a?pd(G(a)):pd());ke.call(this,this.v.u("div",{style:"position:absolute;display:none;"}));this.Hb=new E(1,1);this.ha=new jc;a&&this.eb(a);if(b!=k)if(a=this.c(),"textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(;c=a.firstChild;)a.removeChild(c);a.appendChild(F(a).createTextNode(b))}}y(J,ke);var le=[];r=J.prototype;r.p=k;r.className="goog-tooltip";
r.Lc=500;r.Xc=0;r.Ma=o("v");r.eb=function(a){a=G(a);this.ha.add(a);C(a,"mouseover",this.Oa,l,this);C(a,"mouseout",this.mb,l,this);C(a,"mousemove",this.mc,l,this);C(a,"focus",this.lb,l,this);C(a,"blur",this.mb,l,this)};r.detach=function(a){if(a)a=G(a),me(this,a),this.ha.remove(a);else{for(var b=this.ha.ja(),c=0;a=b[c];c++)me(this,a);this.ha.clear()}};function me(a,b){Vb(b,"mouseover",a.Oa,l,a);Vb(b,"mouseout",a.mb,l,a);Vb(b,"mousemove",a.mc,l,a);Vb(b,"focus",a.lb,l,a);Vb(b,"blur",a.mb,l,a)}
r.Vb=function(a){var b=this.c();b&&vd(b);J.e.Vb.call(this,a);if(a)b=this.v.j.body,b.insertBefore(a,b.lastChild)};r.kb=function(){return this.da?this.D()?4:1:this.Pa?3:this.D()?2:0};r.Rb=function(){if(!ie.prototype.Rb.call(this))return l;if(this.anchor)for(var a,b=0;a=le[b];b++)wd(a.c(),this.anchor)||a.M(l);Ra(le,this)||le.push(this);a=this.c();a.className=this.className;ne(this);C(a,"mouseover",this.qc,l,this);C(a,"mouseout",this.pc,l,this);oe(this);return i};
r.Sb=function(){Sa(le,this);for(var a=this.c(),b,c=0;b=le[c];c++)b.anchor&&wd(a,b.anchor)&&b.M(l);this.Gc&&pe(this.Gc);Vb(a,"mouseover",this.qc,l,this);Vb(a,"mouseout",this.pc,l,this);this.anchor=g;if(this.kb()==0)this.vb=l;ie.prototype.Sb.call(this)};r.Ac=function(a,b){if(this.anchor==a&&this.ha.contains(this.anchor))if(this.vb||!this.vd){if(this.M(l),!this.D())this.anchor=a,this.Tb=b||qe(this,0)||g,this.D()&&this.L(),this.M(i)}else this.anchor=g;this.da=g};
r.ad=function(a){this.Pa=g;a==this.anchor&&(this.p==k||this.p!=this.c()&&!this.ha.contains(this.p))&&(!this.bc||!this.bc.p)&&this.M(l)};function re(a,b){var c=Fd(a.v);a.Hb.x=b.clientX+c.x;a.Hb.y=b.clientY+c.y}r.Oa=function(a){var b=se(this,a.target);this.p=b;ne(this);if(b!=this.anchor){this.anchor=b;if(!this.da)this.da=dc(ra(this.Ac,this,b,g),this.Lc);te(this);re(this,a)}};function se(a,b){try{for(;b&&!a.ha.contains(b);)b=b.parentNode;return b}catch(c){return k}}
r.mc=function(a){re(this,a);this.vb=i};r.lb=function(a){this.p=a=se(this,a.target);this.vb=i;if(this.anchor!=a){this.anchor=a;var b=qe(this,1);ne(this);if(!this.da)this.da=dc(ra(this.Ac,this,a,b),this.Lc);te(this)}};function qe(a,b){if(b==0){var c=a.Hb.H();return new ue(c)}return new ve(a.p)}function te(a){if(a.anchor)for(var b,c=0;b=le[c];c++)if(wd(b.c(),a.anchor))b.bc=a,a.Gc=b}
r.mb=function(a){var b=se(this,a.target),c=se(this,a.relatedTarget);if(b!=c){if(b==this.p)this.p=k;oe(this);this.vb=l;this.D()&&(!a.relatedTarget||!wd(this.c(),a.relatedTarget))?pe(this):this.anchor=g}};r.qc=function(){var a=this.c();if(this.p!=a)ne(this),this.p=a};r.pc=function(a){var b=this.c();if(this.p==b&&(!a.relatedTarget||!wd(b,a.relatedTarget)))this.p=k,pe(this)};function oe(a){if(a.da)cc.clearTimeout(a.da),a.da=g}function pe(a){if(a.kb()==2)a.Pa=dc(ra(a.ad,a,a.anchor),a.Xc)}
function ne(a){if(a.Pa)cc.clearTimeout(a.Pa),a.Pa=g}r.i=function(){this.M(l);oe(this);this.detach();this.c()&&vd(this.c());this.p=k;delete this.v;J.e.i.call(this)};function ue(a,b){fe.call(this,a,b)}y(ue,fe);ue.prototype.L=function(a,b,c){b=Ld(a);b=Od(b);c=c?new hd(c.top+10,c.right,c.bottom,c.left+10):new hd(10,0,0,10);$d(this.Gb,a,4,c,b,9)&496&&$d(this.Gb,a,4,c,b,5)};function ve(a){be.call(this,a,3)}y(ve,be);
ve.prototype.L=function(a,b,c){var e=new E(10,0);Zd(this.element,this.ec,a,b,e,c,9)&496&&Zd(this.element,2,a,1,e,c,5)};function we(){}ga(we);we.prototype.ed=0;we.va();function xe(a){this.v=a||pd();this.Ya=ye}y(xe,bc);xe.prototype.Zc=we.va();var ye=k;function ze(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close"}d(Error("Invalid component state"))}r=xe.prototype;r.ob=k;r.K=l;r.b=k;r.Ya=k;r.bd=k;r.q=k;r.Y=k;r.X=k;r.Nc=l;
function Ae(a,b){if(a.q&&a.q.X){var c=a.q.X,e=a.ob;e in c&&delete c[e];c=a.q.X;b in c&&d(Error('The object already contains the key "'+b+'"'));c[b]=a}a.ob=b}r.c=o("b");function Be(a){return a.xa||(a.xa=new ce(a))}r.getParent=o("q");r.Wb=function(a){this.q&&this.q!=a&&d(Error("Method not supported"));xe.e.Wb.call(this,a)};r.Ma=o("v");r.u=function(){this.b=this.v.createElement("div")};
r.U=function(a){if(this.K)d(Error("Component already rendered"));else if(a&&this.pa(a)){this.Nc=i;if(!this.v||this.v.j!=F(a))this.v=pd(a);this.gc(a);this.ua()}else d(Error("Invalid element to decorate"))};r.pa=q(i);r.gc=ba("b");r.ua=function(){this.K=i;Ce(this,function(a){!a.K&&a.c()&&a.ua()})};r.Ja=function(){Ce(this,function(a){a.K&&a.Ja()});this.xa&&this.xa.ub();this.K=l};
r.i=function(){xe.e.i.call(this);this.K&&this.Ja();this.xa&&(this.xa.J(),delete this.xa);Ce(this,function(a){a.J()});!this.Nc&&this.b&&vd(this.b);this.q=this.bd=this.b=this.X=this.Y=k};r.jb=o("b");r.Ca=function(a){this.K&&d(Error("Component already rendered"));this.Ya=a};function Ce(a,b){a.Y&&Oa(a.Y,b,g)}
r.removeChild=function(a,b){if(a){var c=x(a)?a:a.ob||(a.ob=":"+(a.Zc.ed++).toString(36)),a=this.X&&c?(c in this.X?this.X[c]:g)||k:k;if(c&&a){var e=this.X;c in e&&delete e[c];Sa(this.Y,a);b&&(a.Ja(),a.b&&vd(a.b));c=a;c==k&&d(Error("Unable to set parent component"));c.q=k;xe.e.Wb.call(c,k)}}a||d(Error("Child is not in parent component"));return a};function De(){}var Ee;ga(De);r=De.prototype;r.La=function(){};r.u=function(a){var b=a.Ma().u("div",Fe(this,a).join(" "),a.fa);Ge(this,a,b);return b};r.jb=aa();r.Ia=function(a,b,c){if(a=a.c?a.c():a)if(A&&!vb("7")){var e=He(ld(a),b);e.push(b);sa(c?md:nd,a).apply(k,e)}else c?md(a,b):nd(a,b)};r.pa=q(i);
r.U=function(a,b){b.id&&Ae(a,b.id);var c=this.jb(b);c&&c.firstChild?Ie(a,c.firstChild.nextSibling?Ua(c.childNodes):c.firstChild):a.fa=k;var e=0,f=this.aa(),h=this.aa(),j=l,m=l,c=l,n=ld(b);Oa(n,function(a){if(!j&&a==f)j=i,h==f&&(m=i);else if(!m&&a==h)m=i;else{var b=e;if(!this.Mc){this.gb||Je(this);var c=this.gb,n={},p;for(p in c)n[c[p]]=p;this.Mc=n}a=parseInt(this.Mc[a],10);e=b|(isNaN(a)?0:a)}},this);a.l=e;j||(n.push(f),h==f&&(m=i));m||n.push(h);var p=a.C;p&&n.push.apply(n,p);if(A&&!vb("7")){var s=
He(n);s.length>0&&(n.push.apply(n,s),c=i)}if(!j||!m||p||c)b.className=n.join(" ");Ge(this,a,b);return b};r.tc=function(a){if(a.Ya==k)a.Ya=Qd(a.K?a.b:a.v.j.body);a.Ya&&this.Ca(a.c(),i);a.isEnabled()&&this.wb(a,a.D())};function Ge(a,b,c){b.isEnabled()||a.N(c,1,i);b.l&8&&a.N(c,8,i);b.s&16&&a.N(c,16,!!(b.l&16));b.s&64&&a.N(c,64,!!(b.l&64))}
r.Za=function(a,b){var c=!b,e=A||gb?a.getElementsByTagName("*"):k;if(Vd){if(c=c?"none":"",a.style[Vd]=c,e)for(var f=0,h;h=e[f];f++)h.style[Vd]=c}else if(A||gb)if(c=c?"on":"",a.setAttribute("unselectable",c),e)for(f=0;h=e[f];f++)h.setAttribute("unselectable",c)};r.Ca=function(a,b){this.Ia(a,this.aa()+"-rtl",b)};r.wc=function(a){var b;return a.s&32&&(b=a.ia())?Bd(b):l};
r.wb=function(a,b){var c;if(a.s&32&&(c=a.ia())){if(!b&&a.l&32){try{c.blur()}catch(e){}a.l&32&&a.jc()}if(Bd(c)!=b)b?c.tabIndex=0:(c.tabIndex=-1,c.removeAttribute("tabIndex"))}};r.M=function(a,b){Ud(a,b)};r.B=function(a,b,c){var e=a.c();if(e){var f=Ke(this,b);f&&this.Ia(a,f,c);this.N(e,b,c)}};r.N=function(a,b,c){Ee||(Ee={1:"disabled",8:"selected",16:"checked",64:"expanded"});(b=Ee[b])&&a.setAttribute("aria-"+b,c)};r.ia=function(a){return a.c()};r.aa=q("goog-control");
function Fe(a,b){var c=a.aa(),e=[c],f=a.aa();f!=c&&e.push(f);c=b.kb();for(f=[];c;){var h=c&-c;f.push(Ke(a,h));c&=~h}e.push.apply(e,f);(c=b.C)&&e.push.apply(e,c);A&&!vb("7")&&e.push.apply(e,He(e));return e}function He(a,b){var c=[];b&&(a=a.concat([b]));Oa([],function(e){Qa(e,sa(Ra,a))&&(!b||Ra(e,b))&&c.push(e.join("_"))});return c}function Ke(a,b){a.gb||Je(a);return a.gb[b]}
function Je(a){var b=a.aa();a.gb={1:b+"-disabled",2:b+"-hover",4:b+"-active",8:b+"-selected",16:b+"-checked",32:b+"-focused",64:b+"-open"}};function Le(){}y(Le,De);ga(Le);r=Le.prototype;r.La=q("button");r.N=function(a,b,c){b==16?a.setAttribute("aria-pressed",c):Le.e.N.call(this,a,b,c)};r.u=function(a){var b=Le.e.u.call(this,a),c=a.Na();c&&this.Xb(b,c);(c=a.wa())&&this.xb(b,c);a.s&16&&this.N(b,16,!!(a.l&16));return b};r.U=function(a,b){var b=Le.e.U.call(this,a,b),c=this.wa(b);a.Zb=c;a.Yb=this.Na(b);a.s&16&&this.N(b,16,!!(a.l&16));return b};r.wa=fa;r.xb=fa;r.Na=function(a){return a.title};r.Xb=function(a,b){if(a)a.title=b||""};r.aa=q("goog-button");function Me(a,b){a&&this.eb(a,b)}y(Me,bc);r=Me.prototype;r.b=k;r.qb=k;r.Pb=k;r.rb=k;r.ca=-1;r.ba=-1;
var Ne={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Oe={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Pe={61:187,59:186},Qe=A||B&&vb("525");r=Me.prototype;
r.Uc=function(a){if(B&&(this.ca==17&&!a.ctrlKey||this.ca==18&&!a.altKey))this.ba=this.ca=-1;Qe&&!ge(a.keyCode,this.ca,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.ba=hb&&a.keyCode in Pe?Pe[a.keyCode]:a.keyCode};r.Wc=function(){this.ba=this.ca=-1};
r.handleEvent=function(a){var b=a.w,c,e;A&&a.type=="keypress"?(c=this.ba,e=c!=13&&c!=27?b.keyCode:0):B&&a.type=="keypress"?(c=this.ba,e=b.charCode>=0&&b.charCode<63232&&he(c)?b.charCode:0):gb?(c=this.ba,e=he(c)?b.keyCode:0):(c=b.keyCode||this.ba,e=b.charCode||0,bb&&e==63&&!c&&(c=191));var f=c,h=b.keyIdentifier;c?c>=63232&&c in Ne?f=Ne[c]:c==25&&a.shiftKey&&(f=9):h&&h in Oe&&(f=Oe[h]);a=f==this.ca;this.ca=f;b=new Re(f,e,a,b);try{this.dispatchEvent(b)}finally{b.J()}};r.c=o("b");
r.eb=function(a,b){this.rb&&this.detach();this.b=a;this.qb=C(this.b,"keypress",this,b);this.Pb=C(this.b,"keydown",this.Uc,b,this);this.rb=C(this.b,"keyup",this.Wc,b,this)};r.detach=function(){if(this.qb)Xb(this.qb),Xb(this.Pb),Xb(this.rb),this.rb=this.Pb=this.qb=k;this.b=k;this.ba=this.ca=-1};r.i=function(){Me.e.i.call(this);this.detach()};function Re(a,b,c,e){e&&this.Ra(e,g);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}y(Re,Db);function Se(a,b){a||d(Error("Invalid class name "+a));ja(b)||d(Error("Invalid decorator function "+b));Te[a]=b}var Ue={},Te={};function Ve(a){var b;a:{for(var c=ld(a),e=0,f=c.length;e<f;e++)if(b=c[e]in Te?Te[c[e]]():k)break a;b=k}b&&b.U(a);return b};function We(a,b,c){xe.call(this,c);if(!b){for(var b=this.constructor,e;b;){e=la(b);if(e=Ue[e])break;b=b.e?b.e.constructor:k}b=e?ja(e.va)?e.va():new e:k}this.h=b;this.fa=a}y(We,xe);r=We.prototype;r.fa=k;r.l=0;r.s=39;r.Db=255;r.nd=0;r.zb=i;r.C=k;r.Mb=i;r.cb=l;r.Hc=k;function Xe(a){a.K&&l!=a.Mb&&Ye(a,l);a.Mb=l}r.ia=function(){return this.h.ia(this)};
r.Ia=function(a,b){if(b){if(a)this.C?Ra(this.C,a)||this.C.push(a):this.C=[a],this.h.Ia(this,a,i)}else if(a&&this.C){Sa(this.C,a);if(this.C.length==0)this.C=k;this.h.Ia(this,a,l)}};r.u=function(){var a=this.h.u(this);this.b=a;var b=this.Hc||this.h.La();if(b)a.setAttribute("role",b),a.kd=b;this.cb||this.h.Za(a,l);this.D()||this.h.M(a,l)};r.jb=function(){return this.h.jb(this.c())};r.pa=function(a){return this.h.pa(a)};
r.gc=function(a){this.b=a=this.h.U(this,a);var b=this.Hc||this.h.La();if(b){var c=a;c.setAttribute("role",b);c.kd=b}this.cb||this.h.Za(a,l);this.zb=a.style.display!="none"};r.ua=function(){We.e.ua.call(this);this.h.tc(this);if(this.s&-2&&(this.Mb&&Ye(this,i),this.s&32)){var a=this.ia();if(a){var b=this.za||(this.za=new Me);b.eb(a);H(H(H(Be(this),b,"key",this.Vc),a,"focus",this.lb),a,"blur",this.jc)}}};
function Ye(a,b){var c=Be(a),e=a.c();b?(H(H(H(H(c,e,"mouseover",a.Oa),e,"mousedown",a.lc),e,"mouseup",a.oc),e,"mouseout",a.nc),A&&H(c,e,"dblclick",a.kc)):(ee(ee(ee(ee(c,e,"mouseover",a.Oa),e,"mousedown",a.lc),e,"mouseup",a.oc),e,"mouseout",a.nc),A&&ee(c,e,"dblclick",a.kc))}r.Ja=function(){We.e.Ja.call(this);this.za&&this.za.detach();this.D()&&this.isEnabled()&&this.h.wb(this,l)};r.i=function(){We.e.i.call(this);this.za&&(this.za.J(),delete this.za);delete this.h;this.C=this.fa=k};
function Ie(a,b){a.fa=b}function Ze(a){a=a.fa;if(!a)return"";if(!x(a))if(ha(a))a=Pa(a,Cd).join("");else{if(kd&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Dd(a,b,i);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");kd||(a=a.replace(/ +/g," "));a!=" "&&(a=a.replace(/^\s*/,""))}return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")}r.Ca=function(a){We.e.Ca.call(this,a);var b=this.c();b&&this.h.Ca(b,a)};
r.Za=function(a){this.cb=a;var b=this.c();b&&this.h.Za(b,a)};r.D=o("zb");r.M=function(a,b){if(b||this.zb!=a&&this.dispatchEvent(a?"show":"hide")){var c=this.c();c&&this.h.M(c,a);this.isEnabled()&&this.h.wb(this,a);this.zb=a;return i}return l};r.isEnabled=function(){return!(this.l&1)};function $e(a,b){af(a,2,b)&&a.B(2,b)}r.vc=function(){return!!(this.l&4)};r.setActive=function(a){af(this,4,a)&&this.B(4,a)};r.kb=o("l");
r.B=function(a,b){if(this.s&a&&b!=!!(this.l&a))this.h.B(this,a,b),this.l=b?this.l|a:this.l&~a};function bf(a){a.K&&a.l&32&&d(Error("Component already rendered"));a.l&32&&a.B(32,l);a.s&=-33}function K(a,b){return!!(a.Db&b)&&!!(a.s&b)}function af(a,b,c){return!!(a.s&b)&&!!(a.l&b)!=c&&(!(a.nd&b)||a.dispatchEvent(ze(b,c)))&&!a.Ib}r.Oa=function(a){(!a.relatedTarget||!wd(this.c(),a.relatedTarget))&&this.dispatchEvent("enter")&&this.isEnabled()&&K(this,2)&&$e(this,i)};
r.nc=function(a){if((!a.relatedTarget||!wd(this.c(),a.relatedTarget))&&this.dispatchEvent("leave"))K(this,4)&&this.setActive(l),K(this,2)&&$e(this,l)};r.lc=function(a){if(this.isEnabled()&&(K(this,2)&&$e(this,i),Fb(a)&&(!B||!bb||!a.ctrlKey)))K(this,4)&&this.setActive(i),this.h.wc(this)&&this.ia().focus();!this.cb&&Fb(a)&&(!B||!bb||!a.ctrlKey)&&a.preventDefault()};r.oc=function(a){this.isEnabled()&&(K(this,2)&&$e(this,i),this.vc()&&this.Wa(a)&&K(this,4)&&this.setActive(l))};
r.kc=function(a){this.isEnabled()&&this.Wa(a)};r.Wa=function(a){if(K(this,16)){var b=!(this.l&16);af(this,16,b)&&this.B(16,b)}K(this,8)&&af(this,8,i)&&this.B(8,i);K(this,64)&&(b=!(this.l&64),af(this,64,b)&&this.B(64,b));b=new Bb("action",this);if(a)for(var c=["altKey","ctrlKey","metaKey","shiftKey","platformModifierKey"],e,f=0;e=c[f];f++)b[e]=a[e];return this.dispatchEvent(b)};r.lb=function(){K(this,32)&&af(this,32,i)&&this.B(32,i)};
r.jc=function(){K(this,4)&&this.setActive(l);K(this,32)&&af(this,32,l)&&this.B(32,l)};r.Vc=function(a){return this.D()&&this.isEnabled()&&this.Lb(a)?(a.preventDefault(),a.stopPropagation(),i):l};r.Lb=function(a){return a.keyCode==13&&this.Wa(a)};ja(We)||d(Error("Invalid component class "+We));ja(De)||d(Error("Invalid renderer class "+De));var cf=la(We);Ue[cf]=De;Se("goog-control",function(){return new We(k)});function df(){}y(df,Le);ga(df);r=df.prototype;r.La=function(){};r.u=function(a){Xe(a);a.Db&=-256;bf(a);return a.Ma().u("button",{"class":Fe(this,a).join(" "),disabled:!a.isEnabled(),title:a.Na()||"",value:a.wa()||""},Ze(a)||"")};r.pa=function(a){return a.tagName=="BUTTON"||a.tagName=="INPUT"&&(a.type=="button"||a.type=="submit"||a.type=="reset")};r.U=function(a,b){Xe(a);a.Db&=-256;bf(a);b.disabled&&md(b,Ke(this,1));return df.e.U.call(this,a,b)};r.tc=function(a){H(Be(a),a.c(),"click",a.Wa)};r.Za=fa;
r.Ca=fa;r.wc=function(a){return a.isEnabled()};r.wb=fa;r.B=function(a,b,c){df.e.B.call(this,a,b,c);if((a=a.c())&&b==1)a.disabled=c};r.wa=function(a){return a.value};r.xb=function(a,b){if(a)a.value=b};r.N=fa;function ef(a,b,c){We.call(this,a,b||df.va(),c)}y(ef,We);r=ef.prototype;r.wa=o("Zb");r.xb=function(a){this.Zb=a;this.h.xb(this.c(),a)};r.Na=o("Yb");r.Xb=function(a){this.Yb=a;this.h.Xb(this.c(),a)};r.i=function(){ef.e.i.call(this);delete this.Zb;delete this.Yb};r.ua=function(){ef.e.ua.call(this);if(this.s&32){var a=this.ia();a&&H(Be(this),a,"keyup",this.Lb)}};r.Lb=function(a){return a.keyCode==13&&a.type=="key"||a.keyCode==32&&a.type=="keyup"?this.Wa(a):a.keyCode==32};Se("goog-button",function(){return new ef(k)});function ff(){}y(ff,Le);ga(ff);r=ff.prototype;r.u=function(a){var b={"class":"goog-inline-block "+Fe(this,a).join(" "),title:a.Na()||""};return a.Ma().u("div",b,a.fa)};r.La=q("button");r.pa=function(a){return a.tagName=="DIV"};r.U=function(a,b){md(b,"goog-inline-block");return ff.e.U.call(this,a,b)};r.wa=q(k);r.aa=q("goog-flat-button");Se("goog-flat-button",function(){return new ef(k,ff.va())});function L(a){return a!=k&&a!==l}function gf(a,b){var c=a[v.call(k,b)];return L(c)?c:(c=a._,L(c)?c:l)}function N(a,b){return Error.call(k,"No protocol method "+a+" defined for type "+v.call(k,b)+": "+b)}function hf(a){return Array.prototype.slice.call(a)}function jf(a){return Array.prototype.slice.call(arguments)}function P(a){if(L(L(a)?a.ea:a))a=a.ea(a);else{var b;var c=P[v.call(k,a)];L(c)?b=c:(c=P._,L(c)?b=c:d(N.call(k,"ICounted.-count",a)));a=b.call(k,a)}return a}
function kf(a,b){var c;if(L(L(a)?a.P:a))c=a.P(a,b);else{var e=kf[v.call(k,a)];L(e)?c=e:(e=kf._,L(e)?c=e:d(N.call(k,"ICollection.-conj",a)));c=c.call(k,a,b)}return c}
var Q=function(){return function(a,b,c){switch(arguments.length){case 2:var e;if(L(L(a)?a.Fa:a))e=a.Fa(a,b);else{var f=Q[v.call(k,a)];L(f)?e=f:(f=Q._,L(f)?e=f:d(N.call(k,"IIndexed.-nth",a)));e=e.call(k,a,b)}return e;case 3:return L(L(a)?a.Fa:a)?e=a.Fa(a,b,c):(e=Q[v.call(k,a)],L(e)?f=e:(e=Q._,L(e)?f=e:d(N.call(k,"IIndexed.-nth",a))),e=f.call(k,a,b,c)),e}d("Invalid arity: "+arguments.length)}}(),lf={};
function mf(a){if(L(L(a)?a.ra:a))a=a.ra(a);else{var b;var c=mf[v.call(k,a)];L(c)?b=c:(c=mf._,L(c)?b=c:d(N.call(k,"ISeq.-first",a)));a=b.call(k,a)}return a}function nf(a){if(L(L(a)?a.sa:a))a=a.sa(a);else{var b;var c=nf[v.call(k,a)];L(c)?b=c:(c=nf._,L(c)?b=c:d(N.call(k,"ISeq.-rest",a)));a=b.call(k,a)}return a}
var R=function(){return function(a,b,c){switch(arguments.length){case 2:var e;if(L(L(a)?a.qa:a))e=a.qa(a,b);else{var f=R[v.call(k,a)];L(f)?e=f:(f=R._,L(f)?e=f:d(N.call(k,"ILookup.-lookup",a)));e=e.call(k,a,b)}return e;case 3:return L(L(a)?a.qa:a)?e=a.qa(a,b,c):(e=R[v.call(k,a)],L(e)?f=e:(e=R._,L(e)?f=e:d(N.call(k,"ILookup.-lookup",a))),e=f.call(k,a,b,c)),e}d("Invalid arity: "+arguments.length)}}();
function of(a,b,c){if(L(L(a)?a.hb:a))a=a.hb(a,b,c);else{var e;var f=of[v.call(k,a)];L(f)?e=f:(f=of._,L(f)?e=f:d(N.call(k,"IAssociative.-assoc",a)));a=e.call(k,a,b,c)}return a}var pf={},qf={},rf={};function sf(a){if(L(L(a)?a.Z:a))a=a.g;else{var b;var c=sf[v.call(k,a)];L(c)?b=c:(c=sf._,L(c)?b=c:d(N.call(k,"IMeta.-meta",a)));a=b.call(k,a)}return a}
function tf(a,b){var c;if(L(L(a)?a.$:a))c=a.$(a,b);else{var e=tf[v.call(k,a)];L(e)?c=e:(e=tf._,L(e)?c=e:d(N.call(k,"IWithMeta.-with-meta",a)));c=c.call(k,a,b)}return c}
var uf=function(){return function(a,b,c){switch(arguments.length){case 2:var e;if(L(L(a)?a.Ga:a))e=a.Ga(a,b);else{var f=uf[v.call(k,a)];L(f)?e=f:(f=uf._,L(f)?e=f:d(N.call(k,"IReduce.-reduce",a)));e=e.call(k,a,b)}return e;case 3:return L(L(a)?a.Ga:a)?e=a.Ga(a,b,c):(e=uf[v.call(k,a)],L(e)?f=e:(e=uf._,L(e)?f=e:d(N.call(k,"IReduce.-reduce",a))),e=f.call(k,a,b,c)),e}d("Invalid arity: "+arguments.length)}}();
function vf(a,b){var c;if(L(L(a)?a.t:a))c=a.t(a,b);else{var e=vf[v.call(k,a)];L(e)?c=e:(e=vf._,L(e)?c=e:d(N.call(k,"IEquiv.-equiv",a)));c=c.call(k,a,b)}return c}function wf(a){if(L(L(a)?a.Q:a))a=a.Q(a);else{var b;var c=wf[v.call(k,a)];L(c)?b=c:(c=wf._,L(c)?b=c:d(N.call(k,"IHash.-hash",a)));a=b.call(k,a)}return a}function xf(a){if(L(L(a)?a.T:a))a=a.T(a);else{var b;var c=xf[v.call(k,a)];L(c)?b=c:(c=xf._,L(c)?b=c:d(N.call(k,"ISeqable.-seq",a)));a=b.call(k,a)}return a}var yf={},zf={};
function Af(a,b){var c;if(L(L(a)?a.G:a))c=a.G(a,b);else{var e=Af[v.call(k,a)];L(e)?c=e:(e=Af._,L(e)?c=e:d(N.call(k,"IPrintable.-pr-seq",a)));c=c.call(k,a,b)}return c}function Bf(a,b){return a===b}function S(a,b){return vf.call(k,a,b)}function Cf(a){return Bf.call(k,a,k)}wf["null"]=q(0);R["null"]=function(){return function(a,b,c){switch(arguments.length){case 2:return k;case 3:return c}d("Invalid arity: "+arguments.length)}}();of["null"]=function(a,b,c){return Df.call(k,b,c)};
kf["null"]=function(a,b){return T.call(k,b)};uf["null"]=function(){return function(a,b,c){switch(arguments.length){case 2:return b.call(k);case 3:return c}d("Invalid arity: "+arguments.length)}}();zf["null"]=i;Af["null"]=function(){return T.call(k,"nil")};P["null"]=q(0);lf["null"]=i;mf["null"]=q(k);nf["null"]=function(){return T.call(k)};vf["null"]=function(a,b){return Cf.call(k,b)};tf["null"]=q(k);rf["null"]=i;sf["null"]=q(k);
Q["null"]=function(){return function(a,b,c){switch(arguments.length){case 2:return k;case 3:return c}d("Invalid arity: "+arguments.length)}}();pf["null"]=i;Date.prototype.t=function(a,b){return Bf.call(k,a.toString(),b.toString())};wf.number=aa();vf.number=function(a,b){return Bf.call(k,a,b)};wf["boolean"]=function(a){return a===i?1:0};wf["function"]=function(a){return la.call(k,a)};
var Ef=function(){return function(a,b,c,e){switch(arguments.length){case 2:var f;a:if(L(S.call(k,0,P.call(k,a))))f=b.call(k);else for(var h=Q.call(k,a,0),j=1;;)if(L(j<P.call(k,a)))h=b.call(k,h,Q.call(k,a,j)),j+=1;else{f=h;break a}return f;case 3:a:{f=c;for(j=0;;)if(L(j<P.call(k,a)))f=b.call(k,f,Q.call(k,a,j)),j+=1;else{h=f;break a}}return h;case 4:a:{f=c;for(h=e;;)if(L(h<P.call(k,a)))f=b.call(k,f,Q.call(k,a,h)),h+=1;else{j=f;break a}}return j}d("Invalid arity: "+arguments.length)}}();
function Ff(a,b){this.O=a;this.V=b}r=Ff.prototype;r.Q=function(a){return Gf.call(k,a)};r.Ga=function(){return function(a,b,c){switch(arguments.length){case 2:return Ef.call(k,a,b,this.O[this.V],this.V+1);case 3:return Ef.call(k,a,b,c,this.V)}d("Invalid arity: "+arguments.length)}}();r.P=function(a,b){return U.call(k,b,a)};r.t=function(a,b){return Hf.call(k,a,b)};r.ta=i;
r.Fa=function(){return function(a,b,c){switch(arguments.length){case 2:var e=b+this.V;return L(e<this.O.length)?this.O[e]:k;case 3:return e=b+this.V,L(e<this.O.length)?this.O[e]:c}d("Invalid arity: "+arguments.length)}}();r.ea=function(){return this.O.length-this.V};r.Ha=i;r.ra=function(){return this.O[this.V]};r.sa=function(){return L(this.V+1<this.O.length)?new Ff(this.O,this.V+1):T.call(k)};r.T=aa();function If(a,b){return L(S.call(k,0,a.length))?k:new Ff(a,b)}
function V(a,b){return If.call(k,a,b)}uf.array=function(){return function(a,b,c){switch(arguments.length){case 2:return Ef.call(k,a,b);case 3:return Ef.call(k,a,b,c)}d("Invalid arity: "+arguments.length)}}();R.array=function(){return function(a,b,c){switch(arguments.length){case 2:return a[b];case 3:return Q.call(k,a,b,c)}d("Invalid arity: "+arguments.length)}}();
Q.array=function(){return function(a,b,c){switch(arguments.length){case 2:return L(b<a.length)?a[b]:k;case 3:return L(b<a.length)?a[b]:c}d("Invalid arity: "+arguments.length)}}();P.array=function(a){return a.length};xf.array=function(a){return V.call(k,a,0)};function W(a){return L(a)?xf.call(k,a):k}function X(a){a=W.call(k,a);return L(a)?mf.call(k,a):k}function Y(a){return nf.call(k,W.call(k,a))}function Z(a){return L(a)?W.call(k,Y.call(k,a)):k}function Jf(a){return X.call(k,Z.call(k,a))}
function Kf(a){return Z.call(k,Z.call(k,a))}P._=function(a){for(var a=W.call(k,a),b=0;;)if(L(a))a=Z.call(k,a),b+=1;else return b};vf._=function(a,b){return Bf.call(k,a,b)};function Lf(a){return L(a)?l:i}
var Mf=function(){var a=k,b=function(){function b(a,c,j){var m=k;u(j)&&(m=V(Array.prototype.slice.call(arguments,2),0));return e.call(this,a,c,m)}function e(b,c,e){for(;;)if(L(e))b=a.call(k,b,c),c=X.call(k,e),e=Z.call(k,e);else return a.call(k,b,c)}b.d=2;b.a=function(a){var b=X(a),c=X(Z(a)),a=Y(Z(a));return e.call(this,b,c,a)};return b}(),a=function(a,e,f){switch(arguments.length){case 2:return kf.call(k,a,e);default:return b.apply(this,arguments)}d("Invalid arity: "+arguments.length)};a.d=2;a.a=
b.a;return a}();function Nf(a){return P.call(k,a)}
var Of=function(){return function(a,b,c){switch(arguments.length){case 2:return R.call(k,a,b);case 3:return R.call(k,a,b,c)}d("Invalid arity: "+arguments.length)}}(),Pf=function(){var a=k,b=function(){function b(a,c,j,m){var n=k;u(m)&&(n=V(Array.prototype.slice.call(arguments,3),0));return e.call(this,a,c,j,n)}function e(b,c,e,m){for(;;)if(b=a.call(k,b,c,e),L(m))c=X.call(k,m),e=Jf.call(k,m),m=Kf.call(k,m);else return b}b.d=3;b.a=function(a){var b=X(a),c=X(Z(a)),m=X(Z(Z(a))),a=Y(Z(Z(a)));return e.call(this,
b,c,m,a)};return b}(),a=function(a,e,f,h){switch(arguments.length){case 3:return of.call(k,a,e,f);default:return b.apply(this,arguments)}d("Invalid arity: "+arguments.length)};a.d=3;a.a=b.a;return a}();function Qf(a,b){return tf.call(k,a,b)}function Rf(a){var b;L(a)?(b=a.R,b=L(b)?Lf.call(k,a.hasOwnProperty("cljs$core$IMeta$")):b):b=a;b=L(b)?i:gf.call(k,rf,a);return L(b)?sf.call(k,a):k}function Sf(a){return wf.call(k,a)}
function Tf(a){var b;L(a)?(b=a.ta,b=L(b)?Lf.call(k,a.hasOwnProperty("cljs$core$ISequential$")):b):b=a;return L(b)?i:gf.call(k,yf,a)}function Uf(a){if(L(Cf.call(k,a)))a=l;else{var b;L(a)?(b=a.cc,b=L(b)?Lf.call(k,a.hasOwnProperty("cljs$core$IMap$")):b):b=a;a=L(b)?i:gf.call(k,pf,a)}return a}function Vf(a){var b;L(a)?(b=a.Pc,b=L(b)?Lf.call(k,a.hasOwnProperty("cljs$core$IVector$")):b):b=a;return L(b)?i:gf.call(k,qf,a)}
function Wf(a){var b=jf.call(k);Ib.call(k,a,function(a,e){return b.push(e)});return b}function Xf(a){return g===a}function Yf(a){if(L(Cf.call(k,a)))a=l;else{var b;L(a)?(b=a.Ha,b=L(b)?Lf.call(k,a.hasOwnProperty("cljs$core$ISeq$")):b):b=a;a=L(b)?i:gf.call(k,lf,a)}return a}function Zf(a){return L(a)?i:l}function $f(a){var b=x.call(k,a);return L(b)?Lf.call(k,function(){var b=S.call(k,a.charAt(0),"\ufdd0");return L(b)?b:S.call(k,a.charAt(0),"\ufdd1")}()):b}
function ag(a){var b=x.call(k,a);return L(b)?S.call(k,a.charAt(0),"\ufdd0"):b}function bg(a){var b=x.call(k,a);return L(b)?S.call(k,a.charAt(0),"\ufdd1"):b}
var cg=function(){return function(a,b,c){switch(arguments.length){case 2:return uf.call(k,b,a);case 3:return uf.call(k,c,a,b)}d("Invalid arity: "+arguments.length)}}(),dg=function(){return function(a,b,c){switch(arguments.length){case 2:var e=W.call(k,b);return L(e)?cg.call(k,a,X.call(k,e),Z.call(k,e)):a.call(k);case 3:a:for(var f=b,h=W.call(k,c);;)if(L(h))f=a.call(k,f,X.call(k,h)),h=Z.call(k,h);else{e=f;break a}return e}d("Invalid arity: "+arguments.length)}}();
uf._=function(){return function(a,b,c){switch(arguments.length){case 2:return dg.call(k,b,a);case 3:return dg.call(k,b,c,a)}d("Invalid arity: "+arguments.length)}}();function eg(a,b){for(var c=b,e=W.call(k,a);;){var f=e;if(L(L(f)?c>0:f))c-=1,e=Z.call(k,e);else return e}}Q._=function(){return function(a,b,c){switch(arguments.length){case 2:var e;var f=eg.call(k,a,b);L(f)?e=X.call(k,f):d(Error("Index out of bounds"));return e;case 3:return e=eg.call(k,a,b),L(e)?X.call(k,e):c}d("Invalid arity: "+arguments.length)}}();
var fg=function(){var a=k,b=function(){function b(a,c){var j=k;u(c)&&(j=V(Array.prototype.slice.call(arguments,1),0));return e.call(this,a,j)}function e(b,c){return function(b,c){for(;;)if(L(c))var e=b.append(a.call(k,X.call(k,c))),f=Z.call(k,c),b=e,c=f;else return a.call(k,b)}.call(k,new fd(a.call(k,b)),c)}b.d=1;b.a=function(a){var b=X(a),a=Y(a);return e.call(this,b,a)};return b}(),a=function(a,e){switch(arguments.length){case 0:return"";case 1:return L(Cf.call(k,a))?"":L("\ufdd0'else")?a.toString():
k;default:return b.apply(this,arguments)}d("Invalid arity: "+arguments.length)};a.d=1;a.a=b.a;return a}(),hg=function(){var a=k,b=function(){function a(b,c){var h=k;u(c)&&(h=V(Array.prototype.slice.call(arguments,1),0));return gg.call(k,fg,b,h)}a.d=1;a.a=function(a){var b=X(a),a=Y(a);return gg.call(k,fg,b,a)};return a}(),a=function(a,e){switch(arguments.length){case 0:return"";case 1:return L(bg.call(k,a))?a.substring(2,a.length):L(ag.call(k,a))?fg.call(k,":",a.substring(2,a.length)):L(Cf.call(k,
a))?"":L("\ufdd0'else")?a.toString():k;default:return b.apply(this,arguments)}d("Invalid arity: "+arguments.length)};a.d=1;a.a=b.a;return a}(),ig=function(){return function(a,b,c){switch(arguments.length){case 2:return a.substring(b);case 3:return a.substring(b,c)}d("Invalid arity: "+arguments.length)}}(),jg=function(){var a=k;return a=function(b,c){switch(arguments.length){case 1:return L(ag.call(k,b))?b:L(bg.call(k,b))?fg.call(k,"\ufdd0","'",ig.call(k,b,2)):L("\ufdd0'else")?fg.call(k,"\ufdd0","'",
b):k;case 2:return a.call(k,fg.call(k,b,"/",c))}d("Invalid arity: "+arguments.length)}}();function Hf(a,b){return Zf.call(k,L(Tf.call(k,b))?function(){for(var c=W.call(k,a),e=W.call(k,b);;)if(L(Cf.call(k,c)))return Cf.call(k,e);else if(L(Cf.call(k,e)))return l;else if(L(S.call(k,X.call(k,c),X.call(k,e))))c=Z.call(k,c),e=Z.call(k,e);else return L("\ufdd0'else")?l:k}():k)}function kg(a,b){return a^b+2654435769+(a<<6)+(a>>2)}
function Gf(a){return cg.call(k,function(a,c){return kg.call(k,a,Sf.call(k,c))},Sf.call(k,X.call(k,a)),Z.call(k,a))}function lg(a,b,c,e){this.g=a;this.Ka=b;this.Ba=c;this.I=e}r=lg.prototype;r.Q=function(a){return Gf.call(k,a)};r.ta=i;r.P=function(a,b){return new lg(this.g,b,a,this.I+1)};r.T=aa();r.ea=o("I");r.Ha=i;r.ra=o("Ka");r.sa=o("Ba");r.t=function(a,b){return Hf.call(k,a,b)};r.$=function(a,b){return new lg(b,this.Ka,this.Ba,this.I)};r.R=i;r.Z=o("g");function mg(a){this.g=a}r=mg.prototype;
r.Q=function(a){return Gf.call(k,a)};r.ta=i;r.P=function(a,b){return new lg(this.g,b,k,1)};r.T=q(k);r.ea=q(0);r.Ha=i;r.ra=q(k);r.sa=q(k);r.t=function(a,b){return Hf.call(k,a,b)};r.$=function(a,b){return new mg(b)};r.R=i;r.Z=o("g");var ng=new mg(k);function og(a){return cg.call(k,Mf,ng,a)}var T=function(){function a(a){var c=k;u(a)&&(c=V(Array.prototype.slice.call(arguments,0),0));return cg.call(k,Mf,ng,og.call(k,c))}a.d=0;a.a=function(a){a=W(a);return cg.call(k,Mf,ng,og.call(k,a))};return a}();
function pg(a,b,c){this.g=a;this.Ka=b;this.Ba=c}r=pg.prototype;r.T=aa();r.Q=function(a){return Gf.call(k,a)};r.t=function(a,b){return Hf.call(k,a,b)};r.ta=i;r.P=function(a,b){return new pg(k,b,a)};r.Ha=i;r.ra=o("Ka");r.sa=function(){return L(Cf.call(k,this.Ba))?ng:this.Ba};r.R=i;r.Z=o("g");r.$=function(a,b){return new pg(b,this.Ka,this.Ba)};function U(a,b){return new pg(k,a,b)}
uf.string=function(){return function(a,b,c){switch(arguments.length){case 2:return Ef.call(k,a,b);case 3:return Ef.call(k,a,b,c)}d("Invalid arity: "+arguments.length)}}();R.string=function(){return function(a,b,c){switch(arguments.length){case 2:return Q.call(k,a,b);case 3:return Q.call(k,a,b,c)}d("Invalid arity: "+arguments.length)}}();
Q.string=function(){return function(a,b,c){switch(arguments.length){case 2:return L(b<P.call(k,a))?a.charAt(b):k;case 3:return L(b<P.call(k,a))?a.charAt(b):c}d("Invalid arity: "+arguments.length)}}();P.string=function(a){return a.length};xf.string=function(a){return If.call(k,a,0)};wf.string=function(a){return Ka.call(k,a)};
String.prototype.call=function(){return function(a,b,c){switch(arguments.length){case 2:return Of.call(k,b,this.toString());case 3:return Of.call(k,b,this.toString(),c)}d("Invalid arity: "+arguments.length)}}();String.prototype.apply=function(a,b){return L(Nf.call(k,b)<2)?Of.call(k,b[0],a):Of.call(k,b[0],a,b[1])};function qg(a){var b=a.x;return L(a.Ub)?b:(a.x=b.call(k),a.Ub=i,a.x)}function $(a,b,c){this.g=a;this.Ub=b;this.x=c}r=$.prototype;r.T=function(a){return W.call(k,qg.call(k,a))};
r.Q=function(a){return Gf.call(k,a)};r.t=function(a,b){return Hf.call(k,a,b)};r.ta=i;r.P=function(a,b){return U.call(k,b,a)};r.Ha=i;r.ra=function(a){return X.call(k,qg.call(k,a))};r.sa=function(a){return Y.call(k,qg.call(k,a))};r.R=i;r.Z=o("g");r.$=function(a,b){return new $(b,this.Ub,this.x)};function rg(a){for(var b=jf.call(k);;)if(L(W.call(k,a)))b.push(X.call(k,a)),a=Z.call(k,a);else return b}
function sg(a,b){for(var c=a,e=b,f=0;;){var h;h=e>0;h=L(h)?W.call(k,c):h;if(L(h))c=Z.call(k,c),e-=1,f+=1;else return f}}
var ug=function tg(b){return L(Cf.call(k,b))?k:L(Cf.call(k,Z.call(k,b)))?W.call(k,X.call(k,b)):L("\ufdd0'else")?U.call(k,X.call(k,b),tg.call(k,Z.call(k,b))):k},vg=function(){function a(a,b){return new $(k,l,function(){var c=W.call(k,a);return L(c)?U.call(k,X.call(k,c),e.call(k,Y.call(k,c),b)):b})}function b(a){return new $(k,l,function(){return a})}function c(){return new $(k,l,q(k))}var e=k,f=function(){function a(c,e,f){var h=k;u(f)&&(h=V(Array.prototype.slice.call(arguments,2),0));return b.call(this,
c,e,h)}function b(a,c,f){return function w(a,b){return new $(k,l,function(){var c=W.call(k,a);return L(c)?U.call(k,X.call(k,c),w.call(k,Y.call(k,c),b)):L(b)?w.call(k,X.call(k,b),Z.call(k,b)):k})}.call(k,e.call(k,a,c),f)}a.d=2;a.a=function(a){var c=X(a),e=X(Z(a)),a=Y(Z(a));return b.call(this,c,e,a)};return a}(),e=function(e,j,m){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,e);case 2:return a.call(this,e,j);default:return f.apply(this,arguments)}d("Invalid arity: "+
arguments.length)};e.d=2;e.a=f.a;return e}(),wg=function(){var a=k,b=function(){function a(c,h,j,m,n){var p=k;u(n)&&(p=V(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,h,j,m,p)}function b(a,c,e,m,n){return U.call(k,a,U.call(k,c,U.call(k,e,U.call(k,m,ug.call(k,n)))))}a.d=4;a.a=function(a){var c=X(a),j=X(Z(a)),m=X(Z(Z(a))),n=X(Z(Z(Z(a)))),a=Y(Z(Z(Z(a))));return b.call(this,c,j,m,n,a)};return a}(),a=function(a,e,f,h,j){switch(arguments.length){case 1:return W.call(k,a);case 2:return U.call(k,
a,e);case 3:return U.call(k,a,U.call(k,e,f));case 4:return U.call(k,a,U.call(k,e,U.call(k,f,h)));default:return b.apply(this,arguments)}d("Invalid arity: "+arguments.length)};a.d=4;a.a=b.a;return a}(),gg=function(){var a=k,b=function(){function a(c,h,j,m,n,p){var s=k;u(p)&&(s=V(Array.prototype.slice.call(arguments,5),0));return b.call(this,c,h,j,m,n,s)}function b(a,c,e,m,n,p){c=U.call(k,c,U.call(k,e,U.call(k,m,U.call(k,n,ug.call(k,p)))));e=a.d;return L(a.a)?L(sg.call(k,c,e)<=e)?a.apply(a,rg.call(k,
c)):a.a(c):a.apply(a,rg.call(k,c))}a.d=5;a.a=function(a){var c=X(a),j=X(Z(a)),m=X(Z(Z(a))),n=X(Z(Z(Z(a)))),p=X(Z(Z(Z(Z(a))))),a=Y(Z(Z(Z(Z(a)))));return b.call(this,c,j,m,n,p,a)};return a}(),a=function(a,e,f,h,j,m){switch(arguments.length){case 2:var n=a,p=e,s=n.d;return L(n.a)?L(sg.call(k,p,s+1)<=s)?n.apply(n,rg.call(k,p)):n.a(p):n.apply(n,rg.call(k,p));case 3:return n=a,p=wg.call(k,e,f),s=n.d,L(n.a)?L(sg.call(k,p,s)<=s)?n.apply(n,rg.call(k,p)):n.a(p):n.apply(n,rg.call(k,p));case 4:return n=a,p=wg.call(k,
e,f,h),s=n.d,L(n.a)?L(sg.call(k,p,s)<=s)?n.apply(n,rg.call(k,p)):n.a(p):n.apply(n,rg.call(k,p));case 5:return n=a,p=wg.call(k,e,f,h,j),s=n.d,L(n.a)?L(sg.call(k,p,s)<=s)?n.apply(n,rg.call(k,p)):n.a(p):n.apply(n,rg.call(k,p));default:return b.apply(this,arguments)}d("Invalid arity: "+arguments.length)};a.d=5;a.a=b.a;return a}();function xg(a,b){for(;;)if(L(Cf.call(k,W.call(k,b))))return i;else if(L(a.call(k,X.call(k,b))))var c=a,e=Z.call(k,b),a=c,b=e;else return L("\ufdd0'else")?l:k}
function yg(a){return a}
var zg=function(){function a(a,b,c,f){return new $(k,l,function(){var p=W.call(k,b),s=W.call(k,c),w=W.call(k,f);return L(L(p)?L(s)?w:s:p)?U.call(k,a.call(k,X.call(k,p),X.call(k,s),X.call(k,w)),e.call(k,a,Y.call(k,p),Y.call(k,s),Y.call(k,w))):k})}function b(a,b,c){return new $(k,l,function(){var f=W.call(k,b),p=W.call(k,c);return L(L(f)?p:f)?U.call(k,a.call(k,X.call(k,f),X.call(k,p)),e.call(k,a,Y.call(k,f),Y.call(k,p))):k})}function c(a,b){return new $(k,l,function(){var c=W.call(k,b);return L(c)?
U.call(k,a.call(k,X.call(k,c)),e.call(k,a,Y.call(k,c))):k})}var e=k,f=function(){function a(c,e,f,h,w){var I=k;u(w)&&(I=V(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,e,f,h,I)}function b(a,c,f,h,j){return e.call(k,function(b){return gg.call(k,a,b)},function M(a){return new $(k,l,function(){var b=e.call(k,W,a);return L(xg.call(k,yg,b))?U.call(k,e.call(k,X,b),M.call(k,e.call(k,Y,b))):k})}.call(k,Mf.call(k,j,h,f,c)))}a.d=4;a.a=function(a){var c=X(a),e=X(Z(a)),f=X(Z(Z(a))),h=X(Z(Z(Z(a)))),
a=Y(Z(Z(Z(a))));return b.call(this,c,e,f,h,a)};return a}(),e=function(e,j,m,n,p){switch(arguments.length){case 2:return c.call(this,e,j);case 3:return b.call(this,e,j,m);case 4:return a.call(this,e,j,m,n);default:return f.apply(this,arguments)}d("Invalid arity: "+arguments.length)};e.d=4;e.a=f.a;return e}(),Bg=function Ag(b,c){return new $(k,l,function(){if(L(b>0)){var e=W.call(k,c);return L(e)?U.call(k,X.call(k,e),Ag.call(k,b-1,Y.call(k,e))):k}else return k})};
function Cg(a,b){function c(a,b){for(;;){var c=W.call(k,b),j=a>0;if(L(L(j)?c:j))j=a-1,c=Y.call(k,c),a=j,b=c;else return c}}return new $(k,l,function(){return c.call(k,a,b)})}
var Dg=function(){function a(a){return new $(k,l,function(){return U.call(k,a,b.call(k,a))})}var b=k;return b=function(c,e){switch(arguments.length){case 1:return a.call(this,c);case 2:return Bg.call(k,c,b.call(k,e))}d("Invalid arity: "+arguments.length)}}(),Eg=function(){function a(a,c){return new $(k,l,function(){var h=W.call(k,a),j=W.call(k,c);return L(L(h)?j:h)?U.call(k,X.call(k,h),U.call(k,X.call(k,j),b.call(k,Y.call(k,h),Y.call(k,j)))):k})}var b=k,c=function(){function a(b,e,m){var n=k;u(m)&&
(n=V(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,e,n)}function c(a,e,f){return new $(k,l,function(){var c=zg.call(k,W,Mf.call(k,f,e,a));return L(xg.call(k,yg,c))?vg.call(k,zg.call(k,X,c),gg.call(k,b,zg.call(k,Y,c))):k})}a.d=2;a.a=function(a){var b=X(a),e=X(Z(a)),a=Y(Z(a));return c.call(this,b,e,a)};return a}(),b=function(b,f,h){switch(arguments.length){case 2:return a.call(this,b,f);default:return c.apply(this,arguments)}d("Invalid arity: "+arguments.length)};b.d=2;b.a=c.a;return b}();
function Fg(a,b){return Cg.call(k,1,Eg.call(k,Dg.call(k,a),b))}function Gg(a){return function c(a,f){return new $(k,l,function(){var h=W.call(k,a);return L(h)?U.call(k,X.call(k,h),c.call(k,Y.call(k,h),f)):L(W.call(k,f))?c.call(k,X.call(k,f),Y.call(k,f)):k})}.call(k,k,a)}
var Hg=function(){var a=k,b=function(){function a(b,c,h){var j=k;u(h)&&(j=V(Array.prototype.slice.call(arguments,2),0));return Gg.call(k,gg.call(k,zg,b,c,j))}a.d=2;a.a=function(a){var b=X(a),c=X(Z(a)),a=Y(Z(a));return Gg.call(k,gg.call(k,zg,b,c,a))};return a}(),a=function(a,e,f){switch(arguments.length){case 2:return Gg.call(k,zg.call(k,a,e));default:return b.apply(this,arguments)}d("Invalid arity: "+arguments.length)};a.d=2;a.a=b.a;return a}();function Ig(a,b){return cg.call(k,kf,a,b)}
var Jg=function(){function a(a,b,h,j){return new $(k,l,function(){var m=W.call(k,j);if(L(m)){var n=Bg.call(k,a,m);return L(S.call(k,a,Nf.call(k,n)))?U.call(k,n,c.call(k,a,b,h,Cg.call(k,b,m))):T.call(k,Bg.call(k,a,vg.call(k,n,h)))}else return k})}function b(a,b,h){return new $(k,l,function(){var j=W.call(k,h);if(L(j)){var m=Bg.call(k,a,j);return L(S.call(k,a,Nf.call(k,m)))?U.call(k,m,c.call(k,a,b,Cg.call(k,b,j))):k}else return k})}var c=k;return c=function(e,f,h,j){switch(arguments.length){case 2:return c.call(k,
e,e,f);case 3:return b.call(this,e,f,h);case 4:return a.call(this,e,f,h,j)}d("Invalid arity: "+arguments.length)}}();function Kg(a,b){this.g=a;this.r=b}r=Kg.prototype;r.Q=function(a){return Gf.call(k,a)};r.qa=function(){return function(a,b,c){switch(arguments.length){case 2:return Q.call(k,a,b,k);case 3:return Q.call(k,a,b,c)}d("Invalid arity: "+arguments.length)}}();r.hb=function(a,b,c){a=hf.call(k,this.r);a[b]=c;return new Kg(this.g,a)};r.ta=i;
r.P=function(a,b){var c=hf.call(k,this.r);c.push(b);return new Kg(this.g,c)};r.Ga=function(){return function(a,b,c){switch(arguments.length){case 2:return Ef.call(k,this.r,b);case 3:return Ef.call(k,this.r,b,c)}d("Invalid arity: "+arguments.length)}}();r.T=function(){var a=this;return L(a.r.length>0)?function c(e){return new $(k,l,function(){return L(e<a.r.length)?U.call(k,a.r[e],c.call(k,e+1)):k})}.call(k,0):k};r.ea=function(){return this.r.length};r.Pc=i;r.t=function(a,b){return Hf.call(k,a,b)};
r.$=function(a,b){return new Kg(b,this.r)};r.R=i;r.Z=o("g");r.Fa=function(){return function(a,b,c){switch(arguments.length){case 2:var e=0<=b;return L(L(e)?b<this.r.length:e)?this.r[b]:k;case 3:return e=0<=b,L(L(e)?b<this.r.length:e)?this.r[b]:c}d("Invalid arity: "+arguments.length)}}();var Lg=new Kg(k,jf.call(k));function Mg(a){return new Kg(k,a)}
Kg.prototype.call=function(){return function(a,b,c){switch(arguments.length){case 2:return R.call(k,this,b);case 3:return R.call(k,this,b,c)}d("Invalid arity: "+arguments.length)}}();function Ng(a){return cg.call(k,Mf,Lg,a)}var Og=function(){function a(a){var c=k;u(a)&&(c=V(Array.prototype.slice.call(arguments,0),0));return Ng.call(k,c)}a.d=0;a.a=function(a){a=W(a);return Ng.call(k,a)};return a}();function Pg(){}Pg.prototype.t=q(l);var Qg=new Pg;
function Rg(a,b){return Zf.call(k,L(Uf.call(k,b))?L(S.call(k,Nf.call(k,a),Nf.call(k,b)))?xg.call(k,yg,zg.call(k,function(a){return S.call(k,Of.call(k,b,X.call(k,a),Qg),Jf.call(k,a))},a)):k:k)}function Sg(a,b,c){for(var e=c.length,f=0;;)if(L(f<e))if(L(S.call(k,b,c[f])))return f;else f+=a;else return k}var Tg=function(){var a=k;return a=function(b,c,e,f){switch(arguments.length){case 2:return a.call(k,b,c,i,l);case 4:var h=x.call(k,b);return L(L(h)?c.hasOwnProperty(b):h)?e:f}d("Invalid arity: "+arguments.length)}}();
function Ug(a,b,c){this.g=a;this.keys=b;this.ab=c}r=Ug.prototype;r.Q=function(a){return Gf.call(k,a)};r.qa=function(){return function(a,b,c){switch(arguments.length){case 2:return R.call(k,a,b,k);case 3:return Tg.call(k,b,this.ab,this.ab[b],c)}d("Invalid arity: "+arguments.length)}}();
r.hb=function(a,b,c){if(L(x.call(k,b))){var a=Lb.call(k,this.ab),e=a.hasOwnProperty(b);a[b]=c;return L(e)?new Ug(this.g,this.keys,a):(c=hf.call(k,this.keys),c.push(b),new Ug(this.g,c,a))}else return Qf.call(k,Ig.call(k,Df.call(k,b,c),W.call(k,a)),this.g)};r.P=function(a,b){return L(Vf.call(k,b))?of.call(k,a,Q.call(k,b,0),Q.call(k,b,1)):cg.call(k,kf,a,b)};r.T=function(){var a=this;return L(a.keys.length>0)?zg.call(k,function(b){return Og.call(k,b,a.ab[b])},a.keys):k};r.ea=function(){return this.keys.length};
r.t=function(a,b){return Rg.call(k,a,b)};r.$=function(a,b){return new Ug(b,this.keys,this.ab)};r.R=i;r.Z=o("g");r.cc=i;jf.call(k);function Vg(a,b){return new Ug(k,a,b)}Ug.prototype.call=function(){return function(a,b,c){switch(arguments.length){case 2:return R.call(k,this,b);case 3:return R.call(k,this,b,c)}d("Invalid arity: "+arguments.length)}}();function Wg(a,b,c){this.g=a;this.I=b;this.ka=c}r=Wg.prototype;r.Q=function(a){return Gf.call(k,a)};
r.qa=function(){return function(a,b,c){switch(arguments.length){case 2:return R.call(k,a,b,k);case 3:var e=this.ka[Sf.call(k,b)],f=L(e)?Sg.call(k,2,b,e):k;return L(f)?e[f+1]:c}d("Invalid arity: "+arguments.length)}}();
r.hb=function(a,b,c){var a=Sf.call(k,b),e=this.ka[a];if(L(e)){var e=hf.call(k,e),f=Lb.call(k,this.ka);f[a]=e;a=Sg.call(k,2,b,e);return L(a)?(e[a+1]=c,new Wg(this.g,this.I,f)):(e.push(b,c),new Wg(this.g,this.I+1,f))}else return e=Lb.call(k,this.ka),e[a]=jf.call(k,b,c),new Wg(this.g,this.I+1,e)};r.P=function(a,b){return L(Vf.call(k,b))?of.call(k,a,Q.call(k,b,0),Q.call(k,b,1)):cg.call(k,kf,a,b)};
r.T=function(){var a=this;if(L(a.I>0)){var b=Wf.call(k,a.ka);return Hg.call(k,function(b){return zg.call(k,Ng,Jg.call(k,2,a.ka[b]))},b)}else return k};r.ea=o("I");r.t=function(a,b){return Rg.call(k,a,b)};r.$=function(a,b){return new Wg(b,this.I,this.ka)};r.R=i;r.Z=o("g");r.cc=i;var Xg=new Wg(k,0,function(){return{}}.call(k));Wg.prototype.call=function(){return function(a,b,c){switch(arguments.length){case 2:return R.call(k,this,b);case 3:return R.call(k,this,b,c)}d("Invalid arity: "+arguments.length)}}();
var Df=function(){function a(a){var e=k;u(a)&&(e=V(Array.prototype.slice.call(arguments,0),0));return b.call(this,e)}function b(a){for(var a=W.call(k,a),b=Xg;;)if(L(a))var f=Kf.call(k,a),b=Pf.call(k,b,X.call(k,a),Jf.call(k,a)),a=f;else return b}a.d=0;a.a=function(a){a=W(a);return b.call(this,a)};return a}();Df.call(k);
function Yg(a){if(L($f.call(k,a)))return a;else{var b;b=ag.call(k,a);b=L(b)?b:bg.call(k,a);if(L(b))return b=a.lastIndexOf("/"),L(b<0)?ig.call(k,a,2):ig.call(k,a,b+1);else if(L("\ufdd0'else"))d(Error(hg.call(k,"Doesn't support name: ",a)));else return k}}function Zg(a){var b;b=ag.call(k,a);b=L(b)?b:bg.call(k,a);if(L(b))return b=a.lastIndexOf("/"),L(b>-1)?ig.call(k,a,2,b):k;else d(Error(hg.call(k,"Doesn't support namespace: ",a)))}
function $g(a,b){var c=a.exec(b);return L(S.call(k,X.call(k,c),b))?L(S.call(k,Nf.call(k,c),1))?X.call(k,c):Ng.call(k,c):k}function ah(a,b,c,e,f,h){return vg.call(k,Mg([b]),Gg.call(k,Fg.call(k,Mg([c]),zg.call(k,function(b){return a.call(k,b,f)},h))),Mg([e]))}
var ch=function bh(b,c){return L(Cf.call(k,b))?T.call(k,"nil"):L(Xf.call(k,b))?T.call(k,"#<undefined>"):L("\ufdd0'else")?vg.call(k,L(function(){var e=Of.call(k,c,"\ufdd0'meta");return L(e)?(L(b)?(e=b.R,e=L(e)?Lf.call(k,b.hasOwnProperty("cljs$core$IMeta$")):e):e=b,e=L(e)?i:gf.call(k,rf,b),L(e)?Rf.call(k,b):e):e}())?vg.call(k,Mg(["^"]),bh.call(k,Rf.call(k,b),c),Mg([" "])):k,L(function(){var c;L(b)?(c=b.S,c=L(c)?Lf.call(k,b.hasOwnProperty("cljs$core$IPrintable$")):c):c=b;return L(c)?i:gf.call(k,zf,b)}())?
Af.call(k,b,c):T.call(k,"#<",hg.call(k,b),">")):k};function dh(a,b){var c=X.call(k,a),e=new fd,f=W.call(k,a);if(L(f))for(var h=X.call(k,f);;){L(Bf.call(k,h,c))||e.append(" ");var j=W.call(k,ch.call(k,h,b));if(L(j))for(h=X.call(k,j);;)if(e.append(h),h=Z.call(k,j),L(h))j=h,h=X.call(k,j);else break;f=Z.call(k,f);if(L(f))h=f,f=X.call(k,h),j=h,h=f,f=j;else break}return hg.call(k,e)}
function eh(){return Vg(["\ufdd0'flush-on-newline","\ufdd0'readably","\ufdd0'meta","\ufdd0'dup"],{"\ufdd0'flush-on-newline":i,"\ufdd0'readably":i,"\ufdd0'meta":l,"\ufdd0'dup":l})}var fh=function(){function a(a){var c=k;u(a)&&(c=V(Array.prototype.slice.call(arguments,0),0));return dh.call(k,c,eh.call(k))}a.d=0;a.a=function(a){a=W(a);return dh.call(k,a,eh.call(k))};return a}();Wg.prototype.S=i;
Wg.prototype.G=function(a,b){return ah.call(k,function(a){return ah.call(k,ch,""," ","",b,a)},"{",", ","}",b,a)};zf.number=i;Af.number=function(a){return T.call(k,hg.call(k,a))};Ff.prototype.S=i;Ff.prototype.G=function(a,b){return ah.call(k,ch,"("," ",")",b,a)};$.prototype.S=i;$.prototype.G=function(a,b){return ah.call(k,ch,"("," ",")",b,a)};zf["boolean"]=i;Af["boolean"]=function(a){return T.call(k,hg.call(k,a))};zf.string=i;
Af.string=function(a,b){return L(ag.call(k,a))?T.call(k,hg.call(k,":",function(){var b=Zg.call(k,a);return L(b)?hg.call(k,b,"/"):k}(),Yg.call(k,a))):L(bg.call(k,a))?T.call(k,hg.call(k,function(){var b=Zg.call(k,a);return L(b)?hg.call(k,b,"/"):k}(),Yg.call(k,a))):L("\ufdd0'else")?T.call(k,L("\ufdd0'readably".call(k,b))?Ia.call(k,a):a):k};Kg.prototype.S=i;Kg.prototype.G=function(a,b){return ah.call(k,ch,"["," ","]",b,a)};lg.prototype.S=i;
lg.prototype.G=function(a,b){return ah.call(k,ch,"("," ",")",b,a)};zf.array=i;Af.array=function(a,b){return ah.call(k,ch,"#<Array [",", ","]>",b,a)};mg.prototype.S=i;mg.prototype.G=function(){return T.call(k,"()")};pg.prototype.S=i;pg.prototype.G=function(a,b){return ah.call(k,ch,"("," ",")",b,a)};Ug.prototype.S=i;Ug.prototype.G=function(a,b){return ah.call(k,function(a){return ah.call(k,ch,""," ","",b,a)},"{",", ","}",b,a)};function gh(a,b,c,e){this.state=a;this.g=b;this.xd=c;this.yd=e}r=gh.prototype;
r.S=i;r.G=function(a,b){return vg.call(k,Mg(["#<Atom: "]),Af.call(k,this.state,b),">")};r.R=i;r.Z=o("g");r.t=function(a,b){return Bf.call(k,a,b)};
(function(){var a=k,b=function(){function a(c,h){var j=k;u(h)&&(j=V(Array.prototype.slice.call(arguments,1),0));return b.call(this,c,j)}function b(a,c){var e=L(Yf.call(k,c))?gg.call(k,Df,c):c,m=Of.call(k,e,"\ufdd0'validator"),e=Of.call(k,e,"\ufdd0'meta");return new gh(a,e,m,k)}a.d=1;a.a=function(a){var c=X(a),a=Y(a);return b.call(this,c,a)};return a}(),a=function(a,e){switch(arguments.length){case 1:return new gh(a,k,k,k);default:return b.apply(this,arguments)}d("Invalid arity: "+arguments.length)};
a.d=1;a.a=b.a;return a})().call(k,function(){return Vg(["\ufdd0'parents","\ufdd0'descendants","\ufdd0'ancestors"],{"\ufdd0'parents":Vg([],{}),"\ufdd0'descendants":Vg([],{}),"\ufdd0'ancestors":Vg([],{})})}.call(k));function hh(a){return a.toLowerCase()}function ih(a){return za.call(k,a)}function jh(a){a=hg.call(k,a);var b=Lf.call(k,a);L(b)?a=b:(b=S.call(k,"",a),a=L(b)?b:$g.call(k,/\s+/,a));return L(a)?i:l};var kh,lh;function mh(a,b,c){var e=new gc;e.set("Content-Type","text/plain");return Vc.call(k,a,c,"POST",b,e)}function nh(a){oh.call(k,l);return G.call(k,"output").innerHTML=a}function oh(a){var b=G.call(k,"loading");return L(a)?(nh.call(k,""),b.innerHTML='<img src="images/loading.gif"/>'):b.innerHTML=""}
function ph(){function a(a){for(var b=Vg([],{});;){var c=X.call(k,a);if(L(c))var e=L(S.call(k,c.type,"checkbox"))?c.checked:c.value,e=L(S.call(k,v.call(k,e),"string"))?L(Lf.call(k,jh.call(k,e)))?ih.call(k,e):k:e,a=Z.call(k,a),b=Pf.call(k,b,jg.call(k,c.name),e);else return b}}function b(a){return function(b){return S.call(k,a,hh.call(k,b.nodeName))}}var c=xd.call(k,G.call(k,"settings"),b.call(k,"input")),e=xd.call(k,G.call(k,"selectors"),b.call(k,"textarea"));return Pf.call(k,a.call(k,c),"\ufdd0'selectors",
a.call(k,e))}function qh(a){var b="\ufdd0'selectors".call(k,a);return L(function(){var c="\ufdd0'feed-title".call(k,a);return L(c)?(c="\ufdd0'target-url".call(k,a),L(c)?(c="\ufdd0'headline".call(k,b),L(c)?(c="\ufdd0'title".call(k,b),L(c)?"\ufdd0'link".call(k,b):c):c):c):c}())?a:alert.call(k,"Please fill all mandatory fields.")}function rh(a){a=dd(a.target);return nh.call(k,a)}function sh(){var a=qh.call(k,ph.call(k));return L(a)?(oh.call(k,i),mh.call(k,"/do-test",fh.call(k,a),rh)):k}
function th(a){a=dd(a.target);return nh.call(k,a)}function uh(){var a=qh.call(k,ph.call(k));return L(a)?(oh.call(k,i),a=L(G.call(k,"recaptcha"))?Pf.call(k,Pf.call(k,a,"\ufdd0'challenge",Recaptcha.get_challenge()),"\ufdd0'response",Recaptcha.get_response()):a,L(G.call(k,"recaptcha"))&&Recaptcha.reload(),mh.call(k,"/do-create",fh.call(k,a),th)):k}da("editor.get_link_btn_handler",uh);
da("editor.main",function(){(new J("article-lbl")).c().innerHTML="Headline encompassing element which contains other\r\nheandline elements such as link and title. All other <br/>selectors are applied relative to this element.\r\nYou may select elements with more than one set of selectors,<br/> each set is placed on a distinct line. Selectors from the first line of each field will be used to select one group<br/> of headlines and the\r\ncorresponding member elements and so on. If there is only one line, it will be used in<br/>the all cases.";new J("title-lbl",
"An element containing headline title text.");new J("link-lbl","An 'A' HTML element which 'href' attribute contains a link to the full article.");new J("summary-lbl","An element containing short summary (text or html) of the article.");new J("image-lbl","An 'IMG' HTML element which 'src' attribute contains a link to an article image or photo.");new J("encoding-lbl","Specify this only if encoding of the target HTML-page is not provided by the HTTP protocol.");L(G.call(k,"recaptcha-lbl"))&&new J("recaptcha-lbl",
"It's not necessary to enter confirmation while testing.");L(G.call(k,"excavator-lbl"))&&new J("excavator-lbl","Fully qualified clojure type name of a custom excavator.");L(G.call(k,"parameters-lbl"))&&new J("parameters-lbl","Space separated list of custom excavator constructor parameters (only numbers, strings and keywords are permitted).");new J("recent-article-lbl","Remember the most recent article and do not include headlines below it to the feed (may produce unexpected results).");kh=Ve.call(k,
G.call(k,"test"));C.call(k,kh,"action",sh);lh=Ve.call(k,G.call(k,"save"));return C.call(k,lh,"action",uh)});